/**
 * Nova Zeme L5 Pioneer Projects — shared between the WorldPanel project
 * list and the in-world beacon markers rendered by WorldEnvironment.
 * lat/lon place each beacon on the Nova Zeme globe at its real location.
 */
export const NOVA_ZEME_PROJECTS = [
  {
    id: 'genesis',
    name: 'Zahrada Genesis',
    location: 'Algarve · Portugalsko',
    color: '#10b981',
    status: 'Preparation',
    desc: 'Atlantický uzel Terra Nova — organická farma, glamping, solar off-grid, surf a sázení stromů. První dlouhodobá komunitní infrastruktura.',
    href: 'https://app.zionterranova.com/terranova/genesis',
    lat: 37.0,
    lon: -8.0,
  },
  {
    id: 'dharma',
    name: 'Dharma Temple',
    location: 'La Palma · Kanárské ostrovy',
    color: '#8b5cf6',
    status: 'Preparation',
    desc: 'Spirituální a vzdělávací uzel — meditace, syntropic zahrada, dharma governance, vulkanická krajina, off-grid voda. UNESCO Biosphere Reserve.',
    href: 'https://app.zionterranova.com/terranova/dharma-temple',
    lat: 28.7,
    lon: -17.9,
  },
  {
    id: 'piko-ora',
    name: 'Te Pīko Ora',
    location: 'Tahiti · Francouzská Polynésie',
    color: '#06b6d4',
    status: 'Preparation',
    desc: 'Tichomořský uzel — ochrana mořského i pozemského dědictví, regenerativní komunita, kulturní most mezi Polynésií a ZION.',
    href: 'https://app.zionterranova.com/terranova/te-piko-ora',
    lat: -17.6,
    lon: -149.4,
  },
  {
    id: 'bohemia',
    name: 'Golden Republic Bohemia',
    location: 'Čechy · Česká republika',
    color: '#ffd700',
    status: 'Preparation',
    desc: 'Governance laboratoř Zlaté republiky — kruh rozhodování, česká moudrost (sůl, most, Zlatá bula) a ZION protokol v srdci Evropy.',
    href: 'https://app.zionterranova.com/terranova/golden-republic-bohemia',
    lat: 50.0,
    lon: 15.0,
  },
  {
    id: 'bodhi-lanka',
    name: 'Bodhi Lanka',
    location: 'Srí Lanka',
    color: '#f59e0b',
    status: 'Preparation',
    desc: 'Akáša uzel — prostor, který drží všechny elementy. Nekonečná láska Ramy a Sity, nejstarší žijící strom na Zemi a ZION protokol.',
    href: 'https://app.zionterranova.com/terranova/bodhi-lanka',
    lat: 7.9,
    lon: 80.8,
  },
  {
    id: 'ekam',
    name: 'Ekam · Oneness Temple',
    location: 'Andhra Pradesh · Indie',
    color: '#f5e7b8',
    status: 'Built',
    desc: 'Desátý bod — jediný uzel, který už stojí (2008): bílý mramor, zlatý řez, bezsloupová hala, Zlatá koule. Předloha všech uzlů a vrchol Velké cesty.',
    href: 'https://app.zionterranova.com/terranova/ekam',
    lat: 13.42,
    lon: 79.67,
  },
  {
    id: 'lumi',
    name: 'LUMI · Nová Amerika',
    location: 'Kostarika',
    color: '#14b8a6',
    status: 'Preparation',
    desc: 'Šestý uzel — most mezi Amerikami pro nativní kultury: FPIC kruh starších, semenná knihovna, sdílený pozemek s L6 pozemní stanicí.',
    href: 'https://app.zionterranova.com/terranova/nova-amerika',
    lat: 9.7,
    lon: -83.7,
  },
  {
    id: 'uluru',
    name: 'Uluru',
    location: 'Northern Territory · Austrálie',
    color: '#ea580c',
    status: 'Vision',
    desc: 'Sedmý bod — poselství protinožců: Tjukurpa, songlines, telepatie & vize, propojení s přírodou a zvířaty. Každoroční festival oslavy života.',
    href: 'https://app.zionterranova.com/terranova/uluru',
    lat: -25.3,
    lon: 131.0,
  },
  {
    id: 'maria-del-camino',
    name: 'María del Camino',
    location: 'Světové oceány · Galicie',
    color: '#0ea5e9',
    status: 'Preparation',
    desc: 'Osmý bod — plující uzel: dvě lodě na solárních plachtách (María del Camino × María del Pacífico) spojující všechny uzly po mořském Caminu.',
    href: 'https://app.zionterranova.com/terranova/maria-del-camino',
    lat: 42.4,
    lon: -8.7,
  },
  {
    id: 'boa-esperanca',
    name: 'Boa Esperança',
    location: 'Mys dobré naděje · Jihoafrická republika',
    color: '#f59e0b',
    status: 'Vision',
    desc: 'Devátý bod — šev dvou oceánů, kde se bouře přejmenovává na naději; Khoisan linie, fynbos a kelp les, vodní laboratoř. Uzel jako vztah.',
    href: 'https://app.zionterranova.com/terranova/boa-esperanca',
    lat: -34.35,
    lon: 18.47,
  },
] as const;
