[package]
name = "zionos-miner"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "zionos-miner"
path = "src/main.rs"

[features]
default = []
gpu-opencl = ["dep:ocl"]

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
rayon.workspace = true
num_cpus.workspace = true
zion-core.workspace = true
zion-pool.workspace = true
zion-cosmic-harmony.workspace = true
ureq = { version = "2", features = ["json"] }
ocl = { version = "0.19", optional = true }
