[package]
name = "zion-pool"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
zion-core = { path = "../core" }

[features]
default = []
testnet = []
