// ProgPoWZ (Zano) Metal kernel template.
//
// Runtime-injected placeholders (<random_math> and <data_loads>) are
// generated by the host-side progpow_codegen module and inserted before
// the Metal source is compiled.
//
// The random math sequence is generated by the host-side progpow_codegen
// (port of ProgPow::getKern) and inserted before Metal compilation.
//
// Algorithm: ProgPow 0.9.2 (Zano permutation), 16 lanes, 32 regs,
// 64 DAG rounds, 12 cache loads, 20 math ops, period 50.

#include <metal_stdlib>
using namespace metal;

// ── ProgPow 0.9.2 constants ─────────────────────────────────────────
#define PROGPOW_LANES           16
#define PROGPOW_REGS            32
#define PROGPOW_DAG_LOADS       4
#define PROGPOW_CACHE_BYTES     (16 * 1024)
#define PROGPOW_CACHE_WORDS     (PROGPOW_CACHE_BYTES / 4)
#define PROGPOW_CNT_DAG         64
#define PROGPOW_CNT_CACHE       12
#define PROGPOW_CNT_MATH        20
#define PROGPOW_PERIOD          50

// Dispatch group size must match the kernel's cooperative c_dag load.
#define GROUP_SIZE              128
#define HASHES_PER_GROUP        (GROUP_SIZE / PROGPOW_LANES)

// Number of dag_t groups per lane. The DAG buffer holds
// dag_entries * 8 dag_t entries, so:
//   PROGPOW_DAG_ELEMENTS = (dag_entries * 8) / PROGPOW_LANES = dag_entries / 2
#define PROGPOW_DAG_ELEMENTS    ((uint)(*dag_entries / 2uL))

// ── Utility macros ──────────────────────────────────────────────────
#define ROTL32(x, n) (((x) << ((n) & 31u)) | ((x) >> (((32u) - ((n) & 31u)) & 31u)))
#define ROTR32(x, n) (((x) >> ((n) & 31u)) | ((x) << (((32u) - ((n) & 31u)) & 31u)))
#define mul_hi(a, b) ((uint)(((ulong)(a) * (ulong)(b)) >> 32))
#define fnv1a(h, d) (h = ((h) ^ (d)) * 0x1000193u)

// OpenCL-style type aliases for the generated code.
typedef uint  uint32_t;
typedef ulong uint64_t;

// ── Types ───────────────────────────────────────────────────────────
typedef struct __attribute__((aligned(16))) { uint32_t s[PROGPOW_DAG_LOADS]; } dag_t;

typedef struct {
    uint32_t uint32s[32 / sizeof(uint32_t)];
} hash32_t;

typedef struct {
    uint32_t uint32s[PROGPOW_LANES];
    uint64_t uint64s[PROGPOW_LANES / 2];
} shuffle_t;

// ── Keccak-f[800] constants ─────────────────────────────────────────
constant const uint32_t KECCAKF800_ROT[24] = {
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 2, 14,
    27, 41, 56, 8, 25, 43, 62, 18, 39, 61, 20, 44
};

constant const uint32_t KECCAKF800_PIL[24] = {
    10, 7, 11, 17, 18, 3, 5, 16, 8, 21, 24, 4,
    15, 23, 19, 13, 12, 2, 20, 14, 22, 9, 6, 1
};

constant const uint32_t KECCAKF800_RND[22] = {
    0x00000001u, 0x00008082u, 0x0000808au, 0x80008000u,
    0x0000808bu, 0x80000001u, 0x80008081u, 0x00008009u,
    0x0000008au, 0x00000088u, 0x80008009u, 0x8000000au,
    0x8000808bu, 0x0000008bu, 0x00008089u, 0x00008003u,
    0x00008002u, 0x00000080u, 0x0000800au, 0x8000000au,
    0x80008081u, 0x00008080u
};

// ── Byte-swap a 64-bit value (OpenCL as_ulong(as_uchar8(x).s76543210)) ──
inline uint64_t bswap_ulong(uint64_t x) {
    return ((x & 0xFF00000000000000uL) >> 56) |
           ((x & 0x00FF000000000000uL) >> 40) |
           ((x & 0x0000FF0000000000uL) >> 24) |
           ((x & 0x000000FF00000000uL) >> 8)  |
           ((x & 0x00000000FF000000uL) << 8)  |
           ((x & 0x0000000000FF0000uL) << 24) |
           ((x & 0x000000000000FF00uL) << 40) |
           ((x & 0x00000000000000FFuL) << 56);
}

// ── KISS99 RNG ──────────────────────────────────────────────────────
typedef struct {
    uint32_t z, w, jsr, jcong;
} kiss99_t;

inline uint32_t kiss99(thread kiss99_t* st) {
    st->z = 36969u * (st->z & 0xFFFFu) + (st->z >> 16);
    st->w = 18000u * (st->w & 0xFFFFu) + (st->w >> 16);
    uint32_t mwc = ((st->w << 16) + st->z);
    st->jsr ^= (st->jsr << 17);
    st->jsr ^= (st->jsr >> 13);
    st->jsr ^= (st->jsr << 5);
    st->jcong = 69069u * st->jcong + 1234567u;
    return ((mwc ^ st->jcong) + st->jsr);
}

// ── Keccak-f[800] round ─────────────────────────────────────────────
inline void keccak_f800_round(thread uint32_t st[25], const int r) {
    uint32_t t, bc[5];

    // Theta
    for (int i = 0; i < 5; i++)
        bc[i] = st[i] ^ st[i + 5] ^ st[i + 10] ^ st[i + 15] ^ st[i + 20];

    for (int i = 0; i < 5; i++) {
        t = bc[(i + 4) % 5] ^ ROTL32(bc[(i + 1) % 5], 1u);
        for (uint32_t j = 0; j < 25; j += 5)
            st[j + i] ^= t;
    }

    // Rho Pi
    t = st[1];
    for (int i = 0; i < 24; i++) {
        uint32_t j = KECCAKF800_PIL[i];
        uint32_t tmp = st[j];
        st[j] = ROTL32(t, KECCAKF800_ROT[i]);
        t = tmp;
    }

    // Chi
    for (uint32_t j = 0; j < 25; j += 5) {
        for (int i = 0; i < 5; i++) bc[i] = st[j + i];
        for (int i = 0; i < 5; i++)
            st[j + i] ^= (~bc[(i + 1) % 5]) & bc[(i + 2) % 5];
    }

    // Iota
    st[0] ^= KECCAKF800_RND[r];
}

// ── Keccak-f[800] (64-bit output, byte-swapped) ─────────────────────
inline uint64_t keccak_f800(hash32_t header, uint64_t seed, hash32_t digest) {
    uint32_t st[25];
    for (int i = 0; i < 25; i++) st[i] = 0u;

    for (int i = 0; i < 8; i++) st[i] = header.uint32s[i];
    st[8] = (uint32_t)seed;
    st[9] = (uint32_t)(seed >> 32);
    for (int i = 0; i < 8; i++) st[10 + i] = digest.uint32s[i];

    for (int r = 0; r < 22; r++) keccak_f800_round(st, r);

    uint64_t res = ((uint64_t)st[1] << 32) | (uint64_t)st[0];
    return bswap_ulong(res);
}

// ── Fill per-lane mix registers ─────────────────────────────────────
inline void fill_mix(uint64_t seed, uint32_t lane_id, thread uint32_t mix[PROGPOW_REGS]) {
    uint32_t fnv_hash = 0x811c9dc5u;
    kiss99_t st;
    st.z = fnv1a(fnv_hash, (uint32_t)seed);
    st.w = fnv1a(fnv_hash, (uint32_t)(seed >> 32));
    st.jsr = fnv1a(fnv_hash, lane_id);
    st.jcong = fnv1a(fnv_hash, lane_id);

    #pragma unroll
    for (int i = 0; i < PROGPOW_REGS; i++)
        mix[i] = kiss99(&st);
}

// ── ProgPoWZ mining kernel ──────────────────────────────────────────
//
// Buffer layout (matches AuXpow gpu_metal.rs ProgPow branch):
//   0: header_hash  — device uchar[32]
//   1: target       — device uchar[32]
//   2: dag          — device dag_t[]
//   3: output_nonce — device ulong[1]
//   4: output_hash  — device uchar[32]   (unused by DAG pre-check)
//   5: output_mix   — device uchar[32]
//   6: found        — device atomic_uint[1]
//   7: base_nonce   — constant ulong*
//   8: batch_size   — constant ulong*
//   9: dag_entries  — constant ulong*
//  10: prog_seed    — constant uint*     (unused; math is baked into source)
//
kernel void progpow_zano_mine(
    device const uchar*      header_hash  [[buffer(0)]],
    device const uchar*      target       [[buffer(1)]],
    device const dag_t*      g_dag        [[buffer(2)]],
    device ulong*            output_nonce [[buffer(3)]],
    device uchar*            output_hash  [[buffer(4)]],
    device uchar*            output_mix   [[buffer(5)]],
    device atomic_uint*      found        [[buffer(6)]],
    constant ulong*          base_nonce   [[buffer(7)]],
    constant ulong*          batch_size   [[buffer(8)]],
    constant ulong*          dag_entries  [[buffer(9)]],
    constant uint*           prog_seed    [[buffer(10)]],
    uint                     gid          [[thread_position_in_grid]],
    uint                     lid          [[thread_position_in_threadgroup]]
)
{
    (void)output_hash;
    (void)prog_seed;

    if (atomic_load_explicit(found, memory_order_relaxed) != 0u) return;
    if (gid >= *batch_size) return;

    uint64_t nonce = *base_nonce + (uint64_t)gid;

    // Build 32-byte header hash as little-endian uint32 words.
    hash32_t header;
    #pragma unroll
    for (int i = 0; i < 8; i++) {
        header.uint32s[i] =  (uint32_t)header_hash[i*4]
                          | ((uint32_t)header_hash[i*4+1] << 8)
                          | ((uint32_t)header_hash[i*4+2] << 16)
                          | ((uint32_t)header_hash[i*4+3] << 24);
    }

    // Build 64-bit big-endian target from the first 8 bytes.
    uint64_t target_u64 = 0uL;
    #pragma unroll
    for (int i = 0; i < 8; i++) {
        target_u64 = (target_u64 << 8) | (uint64_t)target[i];
    }

    // Seed = keccak_f800(header || nonce || 0)
    hash32_t digest_zero;
    #pragma unroll
    for (int i = 0; i < 8; i++) digest_zero.uint32s[i] = 0u;
    uint64_t seed = keccak_f800(header, nonce, digest_zero);

    // Cooperative load of the first PROGPOW_CACHE_WORDS DAG words.
    threadgroup shuffle_t share[HASHES_PER_GROUP];
    threadgroup uint32_t c_dag[PROGPOW_CACHE_WORDS];

    for (uint32_t word = lid * PROGPOW_DAG_LOADS;
         word < PROGPOW_CACHE_WORDS;
         word += GROUP_SIZE * PROGPOW_DAG_LOADS)
    {
        dag_t load = g_dag[word / PROGPOW_DAG_LOADS];
        #pragma unroll
        for (int i = 0; i < PROGPOW_DAG_LOADS; i++) {
            c_dag[word + i] = load.s[i];
        }
    }

    uint32_t lane_id = lid & (PROGPOW_LANES - 1);
    uint32_t group_id = lid / PROGPOW_LANES;

    threadgroup_barrier(mem_flags::mem_threadgroup);

    hash32_t digest;

    // Outer lane loop: each lane contributes one share to the mix.
    #pragma unroll 1
    for (int h = 0; h < PROGPOW_LANES; h++)
    {
        // Broadcast seed from lane h to all lanes in the hash group.
        if (lane_id == (uint32_t)h) share[group_id].uint64s[0] = seed;
        threadgroup_barrier(mem_flags::mem_threadgroup);
        uint64_t hash_seed = share[group_id].uint64s[0];

        uint32_t mix[PROGPOW_REGS];
        fill_mix(hash_seed, lane_id, mix);

        // Inner DAG mixing loop.
        #pragma unroll 1
        for (uint32_t l = 0; l < PROGPOW_CNT_DAG; l++)
        {
            // Broadcast mix[0] from lane (l % PROGPOW_LANES).
            if (lane_id == (l % PROGPOW_LANES)) share[group_id].uint64s[0] = (uint64_t)mix[0];
            threadgroup_barrier(mem_flags::mem_threadgroup);

            uint32_t offset = (uint32_t)(share[group_id].uint64s[0] % (uint64_t)PROGPOW_DAG_ELEMENTS);
            offset = offset * PROGPOW_LANES + ((lane_id ^ l) % PROGPOW_LANES);
            dag_t data_dag = g_dag[offset];

            uint32_t data;
            PROGPOW_INCLUDE_RANDOM_MATH
            PROGPOW_INCLUDE_DATA_LOADS
        }

        // Reduce this lane's mix registers to a single 32-bit value.
        uint32_t mix_hash = 0x811c9dc5u;
        #pragma unroll
        for (int i = 0; i < PROGPOW_REGS; i++) {
            fnv1a(mix_hash, mix[i]);
        }

        share[group_id].uint32s[lane_id] = mix_hash;
        threadgroup_barrier(mem_flags::mem_threadgroup);

        // Reduce all lanes into a 256-bit digest.
        hash32_t digest_temp;
        #pragma unroll
        for (int i = 0; i < 8; i++) digest_temp.uint32s[i] = 0x811c9dc5u;
        #pragma unroll
        for (int i = 0; i < PROGPOW_LANES; i++) {
            fnv1a(digest_temp.uint32s[i % 8], share[group_id].uint32s[i]);
        }

        if (lane_id == (uint32_t)h) {
            #pragma unroll
            for (int i = 0; i < 8; i++) digest.uint32s[i] = digest_temp.uint32s[i];
        }
    }

    // Final hash check (64-bit pre-check; full hash recomputed on CPU).
    if (keccak_f800(header, seed, digest) <= target_u64) {
        uint old = atomic_exchange_explicit(found, 1u, memory_order_relaxed);
        if (old == 0u) {
            *output_nonce = nonce;
            #pragma unroll
            for (int i = 0; i < 8; i++) {
                output_mix[i*4]     = (uchar)(digest.uint32s[i]);
                output_mix[i*4 + 1] = (uchar)(digest.uint32s[i] >> 8);
                output_mix[i*4 + 2] = (uchar)(digest.uint32s[i] >> 16);
                output_mix[i*4 + 3] = (uchar)(digest.uint32s[i] >> 24);
            }
        }
    }
}
