FROM node:22-alpine
WORKDIR /app
COPY .next .next
COPY node_modules node_modules
COPY package.json package.json
COPY public public
ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000
CMD ["node", "node_modules/.bin/next", "start"]
