[package]
name = "poc-npu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
poc-core  = { path = "../poc-core" }
poc-hiran = { path = "../poc-hiran" }
serde     = { workspace = true }
thiserror = { workspace = true }
blake3    = { workspace = true }
hex       = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
