#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# ZION Desktop Agent — Build + Publish Release
# ─────────────────────────────────────────────────────────────────────────────
# Usage:
#   ./publish-release.sh <version> [platform]
#
# Examples:
#   ./publish-release.sh 3.0.5 mac        # Build macOS only
#   ./publish-release.sh 3.0.5 win        # Build Windows only
#   ./publish-release.sh 3.0.5 linux      # Build Linux only
#   ./publish-release.sh 3.0.5 all        # Build all platforms
#
# Prerequisites:
#   - UPDATE_ADMIN_TOKEN env var set (for remote server)
#   - UPDATE_RELEASES_DIR env var set (for local filesystem copy)
#   - UPDATE_SERVER_URL env var set (default: http://localhost:3001)
#
# Code signing (optional — when certificates are purchased):
#   Windows: export CSC_LINK, CSC_KEY_PASSWORD
#   macOS:   export CSC_NAME, APPLE_ID, APPLE_APP_SPECIFIC_PASSWORD, APPLE_TEAM_ID
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

VERSION="${1:-}"
PLATFORM="${2:-current}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ -z "$VERSION" ]; then
  echo "Usage: $0 <version> [mac|win|linux|all]"
  echo "Example: $0 3.0.5 mac"
  exit 1
fi

echo "═══════════════════════════════════════════════════════════════"
echo "  ZION Desktop Agent — Build + Publish v${VERSION}"
echo "═══════════════════════════════════════════════════════════════"

# ── Check prerequisites ──────────────────────────────────────────────────────
cd "$AGENT_DIR"

if [ ! -f "package.json" ]; then
  echo "ERROR: package.json not found in $AGENT_DIR"
  exit 1
fi

# Ensure dependencies are installed
if [ ! -d "node_modules" ]; then
  echo "Installing dependencies..."
  npm install
fi

# ── Update version in package.json ───────────────────────────────────────────
echo "Setting version to ${VERSION}..."
npm version "$VERSION" --no-git-tag-version --allow-same-version 2>/dev/null || true

# ── Build ────────────────────────────────────────────────────────────────────
build_platform() {
  local target="$1"
  echo ""
  echo "── Building for ${target} ──"

  case "$target" in
    mac)
      npm run build:mac
      ;;
    win)
      npm run build:win
      ;;
    linux)
      npm run build:linux
      ;;
    all)
      npm run build:all
      ;;
    *)
      echo "ERROR: Unknown platform '$target'"
      exit 1
      ;;
  esac
}

# Determine current platform if not specified
if [ "$PLATFORM" = "current" ]; then
  case "$(uname -s)" in
    Darwin) PLATFORM="mac" ;;
    Linux)  PLATFORM="linux" ;;
    MINGW*|MSYS*|CYGWIN*) PLATFORM="win" ;;
    *) echo "ERROR: Cannot detect platform. Specify manually."; exit 1 ;;
  esac
fi

build_platform "$PLATFORM"

# ── Verify build output ──────────────────────────────────────────────────────
echo ""
echo "── Build output ──"
ls -la dist/ 2>/dev/null || { echo "ERROR: dist/ directory not found"; exit 1; }

# Check for yml files (required for electron-updater)
YML_COUNT=$(find dist/ -name "latest*.yml" 2>/dev/null | wc -l)
if [ "$YML_COUNT" -eq 0 ]; then
  echo "WARNING: No latest*.yml files found in dist/. electron-updater will not work."
  echo "         These files are generated by electron-builder during build."
fi

echo ""
echo "Found $YML_COUNT yml manifest file(s):"
find dist/ -name "latest*.yml" -exec echo "  {}" \;

# ── Upload to update server ──────────────────────────────────────────────────
echo ""
echo "── Publishing to update server ──"

if [ -n "${UPDATE_RELEASES_DIR:-}" ]; then
  # Local filesystem copy
  echo "Copying to local releases dir: $UPDATE_RELEASES_DIR"
  node "$SCRIPT_DIR/upload-release.js" --version "$VERSION" --dir "$AGENT_DIR/dist"
elif [ -n "${UPDATE_ADMIN_TOKEN:-}" ]; then
  # Remote server upload
  echo "Uploading to remote server: ${UPDATE_SERVER_URL:-http://localhost:3001}"
  node "$SCRIPT_DIR/upload-release.js" --version "$VERSION" --dir "$AGENT_DIR/dist"
else
  echo "WARNING: Neither UPDATE_RELEASES_DIR nor UPDATE_ADMIN_TOKEN set."
  echo "         Build artifacts are in dist/ — upload manually to the update server."
  echo ""
  echo "To upload locally:"
  echo "  UPDATE_RELEASES_DIR=/path/to/releases ./publish-release.sh $VERSION $PLATFORM"
  echo ""
  echo "To upload to remote server:"
  echo "  UPDATE_ADMIN_TOKEN=your-token UPDATE_SERVER_URL=https://updates.zionterranova.com ./publish-release.sh $VERSION $PLATFORM"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Release v${VERSION} build + publish complete!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Generate a license key for testing:"
echo "     cd update-server && UPDATE_ADMIN_TOKEN=your-token node scripts/generate-license.js --email test@example.com"
echo "  2. Enter the license key in Desktop Agent → Settings → Updates"
echo "  3. Click 'Check for Updates' to verify the flow"
