use zion_cosmic_harmony::ExternalCoin;

/// A stratum job received from an external (AuxPoW) pool.
#[derive(Clone, Debug)]
pub struct Job {
    pub job_id: String,
    pub coin: ExternalCoin,
    /// Header bytes to be hashed; length is algorithm-specific.
    pub header: Vec<u8>,
    /// 32-byte difficulty target (little-endian comparison).
    pub target: [u8; 32],
    /// ExtraNonce1 provided by the pool for the session.
    pub extranonce: Vec<u8>,
    /// ExtraNonce2 generated by the miner for share uniqueness.
    pub extranonce2: String,
    /// ntime field used when submitting shares (hex, 4 bytes).
    pub ntime: String,
}

impl Default for Job {
    fn default() -> Self {
        Self {
            job_id: String::new(),
            coin: ExternalCoin::Bitcoin,
            header: Vec::new(),
            target: [0u8; 32],
            extranonce: Vec::new(),
            extranonce2: "00".to_string(),
            ntime: "00000000".to_string(),
        }
    }
}

/// A found share ready for submission.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Share {
    pub job_id: String,
    pub coin: ExternalCoin,
    pub nonce: u64,
    pub hash: [u8; 32],
    /// ExtraNonce2 used when submitting the share.
    pub extranonce2: String,
    /// ntime field used when submitting the share.
    pub ntime: String,
}

impl Share {
    pub fn nonce_hex(&self) -> String {
        format!("{:016x}", self.nonce)
    }
}
