<?php
/**
 * ZION Presale Wallet Pool Library
 * ==================================
 * Assigns pre-generated wallets from JSON pool to customers.
 * Fallback when Python API is not accessible from PHP-FPM.
 * 
 * Pool is generated by: python3 api/generate_wallet_pool.py --count 100
 * 
 * Author: ZION Team
 * Version: 3.1.0
 * Date: 28.12.2025
 */

// Configuration
if (!defined('WALLET_POOL_FILE')) {
    define('WALLET_POOL_FILE', __DIR__ . '/../data/presale_wallet_pool.json');
}

if (!defined('WALLET_POOL_MIN_AVAILABLE')) {
    define('WALLET_POOL_MIN_AVAILABLE', 10);  // Alert when below this
}

/**
 * Load wallet pool from JSON file
 * 
 * @return array Pool data
 */
function wallet_pool_load(): array
{
    $file = WALLET_POOL_FILE;
    
    if (!file_exists($file)) {
        throw new RuntimeException("Wallet pool not found: $file. Run: python3 api/generate_wallet_pool.py");
    }
    
    $json = file_get_contents($file);
    $pool = json_decode($json, true);
    
    if (!$pool || !isset($pool['available'])) {
        throw new RuntimeException("Invalid wallet pool format");
    }
    
    return $pool;
}

/**
 * Save wallet pool back to JSON
 * 
 * @param array $pool Pool data
 */
function wallet_pool_save(array $pool): void
{
    $file = WALLET_POOL_FILE;
    
    // Atomic write
    $tmpFile = $file . '.tmp';
    file_put_contents($tmpFile, json_encode($pool, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
    rename($tmpFile, $file);
}

/**
 * Get count of available wallets
 * 
 * @return int Available count
 */
function wallet_pool_available_count(): int
{
    try {
        $pool = wallet_pool_load();
        return count($pool['available'] ?? []);
    } catch (Exception $e) {
        return 0;
    }
}

/**
 * Assign a wallet from pool to customer
 * 
 * @param string $orderId Order ID
 * @param string $email Customer email
 * @param string $name Customer name
 * @param int $tokens Token amount
 * @param string $network Network (testnet/mainnet)
 * @return array Assigned wallet data
 * @throws RuntimeException If no wallets available
 */
function wallet_pool_assign(
    string $orderId,
    string $email,
    string $name,
    int $tokens,
    string $network = 'testnet'
): array {
    $pool = wallet_pool_load();
    
    if (empty($pool['available'])) {
        throw new RuntimeException("No wallets available in pool. Run: python3 api/generate_wallet_pool.py --count 100");
    }
    
    // Take first available wallet
    $wallet = array_shift($pool['available']);
    
    // Mark as assigned
    $wallet['assigned'] = true;
    $wallet['assigned_at'] = date(DATE_ATOM);
    $wallet['order_id'] = $orderId;
    $wallet['customer_email'] = $email;
    $wallet['customer_name'] = $name;
    $wallet['tokens'] = $tokens;
    $wallet['network'] = $network;
    
    // Move to assigned list
    $pool['assigned'][] = $wallet;
    
    // Update metadata
    $pool['metadata']['last_assigned'] = date(DATE_ATOM);
    $pool['metadata']['assigned_count'] = count($pool['assigned']);
    
    // Save pool
    wallet_pool_save($pool);
    
    // Generate QR code with JSON data for mobile app
    $qrImage = null;
    $qrUrl = null;
    
    try {
        $qrDir = __DIR__ . '/../wallets';
        if (!is_dir($qrDir)) {
            mkdir($qrDir, 0755, true);
        }
        
        $qrFile = $qrDir . '/' . $wallet['wallet_id'] . '.png';
        
        // Use PHP QR generator with ZION wallet JSON format
        require_once __DIR__ . '/qr-generator.php';
        
        // Generate QR with full wallet data (JSON format for mobile app)
        $walletData = [
            'wallet_id' => $wallet['wallet_id'],
            'walletId' => $wallet['wallet_id'],
            'address' => $wallet['address'],
            'mnemonic' => $wallet['mnemonic'],
            'tokens' => $tokens,
            'order_id' => $orderId,
            'orderId' => $orderId,
            'network' => $network,
            'created_at' => $wallet['created_at'] ?? date(DATE_ATOM)
        ];
        
        if (generate_wallet_qr_json($walletData, $qrFile, 400)) {
            $qrImage = basename($qrFile);
            $qrUrl = '/V2/wallets/' . $qrImage;
            error_log("✅ QR generated with mnemonic for wallet {$wallet['wallet_id']}");
        } else {
            error_log("⚠️ QR generation failed, trying fallback");
        }
    } catch (Exception $e) {
        // QR generation failed, continue without it
        error_log("QR generation failed: " . $e->getMessage());
    }
    
    // Log assignment
    error_log("✅ Wallet pool: Assigned {$wallet['wallet_id']} to order $orderId ($tokens tokens)");
    
    // Check if pool is running low
    $remaining = count($pool['available']);
    if ($remaining < WALLET_POOL_MIN_AVAILABLE) {
        error_log("⚠️ Wallet pool running low: $remaining wallets remaining");
    }
    
    return [
        'wallet' => [
            'id' => $wallet['wallet_id'],
            'address' => $wallet['address'],
            'mnemonic' => $wallet['mnemonic'],
            'publicKey' => $wallet['public_key'],
            'label' => "ZION Presale Order: $orderId",
            'tokens' => $tokens,
            'orderId' => $orderId,
            'createdAt' => $wallet['created_at'],
            'expiresAt' => $wallet['expires_at'],
            'network' => $network,
            'uri' => $wallet['address']  // Legacy compatibility
        ],
        'qr' => [
            'imageFile' => $qrImage,
            'imageUrl' => $qrUrl,
            'dataUrl' => null
        ],
        'source' => 'pool',
        'pool_remaining' => $remaining
    ];
}

/**
 * Check if wallet pool is available and has wallets
 * 
 * @return bool True if pool can be used
 */
function is_wallet_pool_available(): bool
{
    try {
        return wallet_pool_available_count() > 0;
    } catch (Exception $e) {
        return false;
    }
}

/**
 * Get wallet pool statistics
 * 
 * @return array Stats
 */
function wallet_pool_stats(): array
{
    try {
        $pool = wallet_pool_load();
        return [
            'available' => count($pool['available'] ?? []),
            'assigned' => count($pool['assigned'] ?? []),
            'generated_at' => $pool['metadata']['generated_at'] ?? null,
            'last_assigned' => $pool['metadata']['last_assigned'] ?? null,
            'version' => $pool['metadata']['version'] ?? 'unknown'
        ];
    } catch (Exception $e) {
        return [
            'error' => $e->getMessage(),
            'available' => 0,
            'assigned' => 0
        ];
    }
}
