/* ========================================
   ZION eShop - Produktový katalog
   ======================================== */

const PRODUCTS = [
    // === SEEDS (TEMPORARILY DISABLED) ===
    /*
    {
        id: 'seed-001',
        name: 'PARAMAJOTI HIRANYAGARBHA',
        category: 'seeds',
        description: 'Orion x Gaia. Prémiový léčebný strain s vysokým obsahem CBD. Vhodný pro střední Evropu. Outdoor/Indoor. 5ks regular semínek.',
        price: 390,
        tokens: 390,
        oldPrice: null,
        image: './img/seeds/paramjoti.jpg',
        badge: 'Nové 2025',
        inStock: true,
        size: '5 ks pack',
        stock: 30
    },
    {
        id: 'seed-002',
        name: 'JAGANATH KRISHNA',
        category: 'seeds',
        description: 'Hari x Gaia. Hybridní kmen s vyváženým poměrem THC/CBD. Outdoor/Indoor. 5ks regular semínek',
        price: 390,
        tokens: 390,
        oldPrice: null,
        image: './img/seeds/jaganath.jpg',
        badge: 'Nové 2025',
        inStock: true,
        size: '5 ks pack',
        stock: 30
    },
    {
        id: 'seed-003',
        name: 'RAMAYANA',
        category: 'seeds',
        description: 'Visnu x Gaia. Meditační strain s relaxačními účinky. Ideální pro večerní použití. 5ks regular semínek.',
        price: 390,
        tokens: 390,
        oldPrice: null,
        image: './img/seeds/ramayana.jpg',
        badge: 'Nové 2025',
        inStock: true,
        size: '5 ks pack',
        stock: 30
    },
    {
        id: 'seed-004',
        name: 'E = MC²',
        category: 'seeds',
        description: 'Elephant x Gaia. Energický strain pro kreativitu a fokus. Denní použití. 5ks regular semínek',
        price: 390,
        tokens: 390,
        oldPrice: null,
        image: './img/seeds/emc2.jpg',
        badge: 'Nové 2025',
        inStock: true,
        size: '5 ks pack',
        stock: 30
    },
    {
        id: 'seed-006',
        name: 'Bylinkové konopné semínko - sůl',
        category: 'seeds',
        description: 'Směs konopných semínek, bambusové soli a minerálních látek. Skvělý pomocník do kuchyně!',
        price: 290,
        tokens: 290,
        oldPrice: null,
        image: './img/lotos.jpg',
        badge: 'Kitchen',
        inStock: false,
        size: '150 g mix',
        stock: 0
    },
    */

    // === WOODART ===
    /*
    {
        id: 'wood-001',
        name: 'Gravírované prkénko - Sri Yantra',
        category: 'woodart',
        description: 'Ručně gravírované kuchyňské prkénko z bukového dřeva s motivem posvátné geometrie.',
        price: 890,
        tokens: 890,
        oldPrice: null,
        image: './img/J&H.jpg',
        badge: 'Ruční práce',
        inStock: true,
        size: '40 x 25 cm',
        stock: 12
    },
    {
        id: 'wood-002',
        name: 'Dřevěný box na šperky - Mandala',
        category: 'woodart',
        description: 'Elegantní šperkovnice z jasanového dřeva s laserově gravírovanou mandalou.',
        price: 1290,
        tokens: 1290,
        oldPrice: 1490,
        image: './Folio/assets/img/botnik.jpg',
        badge: 'Sleva',
        inStock: false,
        size: '18 x 18 x 12 cm',
        stock: 7
    },
    */
    {
        id: 'wood-003',
        name: 'Pergola na míru - konzultace',
        category: 'woodart',
        description: 'Profesionální tesařská výroba pergol na míru. Cena za konzultaci.',
        price: 390,
        tokens: 3900,
        oldPrice: null,
        image: './Folio/assets/img/woodwork.jpg',
        badge: 'Projekt',
        inStock: true,
        size: 'Konzultace 60 min',
        stock: 5
    },
    {
        id: 'wood-004',
        name: 'Dětský domek na stromě',
        category: 'woodart',
        description: 'Kompletní realizace dětského domku, konzultace, návrh a stavba na míru.',
        price: 69000,
        tokens: 690000,
        oldPrice: null,
        image: './Folio/assets/img/dom.jpeg',
        badge: 'Projekt',
        inStock: false,
        size: 'Zakázka na míru',
        stock: 3
    },

    // === STARFIGHTERS ===
    {
        id: 'star-001',
        name: 'A-Wing Wooden Starfighter',
        category: 'starfighters',
        description: 'Laser-cutovaný A-Wing kit. Připraveno pro 3mm překližku, STL náhled a PDF instrukce.',
        price: 790,
        tokens: 7900,
        oldPrice: null,
        image: './img/starfighters/awing.png',
        badge: 'CNC Ready',
        inStock: false,
        modelUrl: './models/awing.stl',
        instructionsUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/instr/awing_instructions.pdf',
        filesUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/svg/awing_svg.zip',
        size: 'rozpětí 300 mm',
        stock: 18
    },
    {
        id: 'star-002',
        name: 'B-Wing Wooden Starfighter',
        category: 'starfighters',
        description: 'Ikonický B-Wing v dřevěném provedení. Obsahuje STL podklady i SVG pro okamžité vypalování.',
        price: 1190,
        tokens: 11900,
        oldPrice: null,
        image: './img/starfighters/bwing.png',
        badge: 'Workshop',
        inStock: false,
        modelUrl: './models/bwing.stl',
        instructionsUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/instr/bwing_instructions.pdf',
        filesUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/svg/bwing_svg.zip',
        size: 'rozpětí 35 mm',
        stock: 14
    },
    {
        id: 'star-003',
        name: 'X-Wing Wooden Starfighter',
        category: 'starfighters',
        description: 'Nejžádanější X-Wing sada. Detailní křídla + kompletní PDF pro přesnou montáž.',
        price: 1090,
        tokens: 10900,
        oldPrice: 1690,
        image: './img/starfighters/xwing.png',
        badge: 'Bestseller',
        inStock: false,
        modelUrl: './models/xwing.stl',
        instructionsUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/instr/xwing_instructions.pdf',
        filesUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/svg/xwing_svg.zip',
        size: 'rozpětí 300 mm',
        stock: 20
    },
    {
        id: 'star-004',
        name: 'Ikaruga Wooden Starfighter',
        category: 'starfighters',
        description: 'Legendární Ikaruga v elegantním geometrickém designu. 3D STL obsahuje originální detaily.',
        price: 890,
        tokens: 8900,
        oldPrice: null,
        image: './img/starfighters/ikaruga.png',
        badge: 'Arcade Icon',
        inStock: false,
        modelUrl: './models/ikaruga.stl',
        instructionsUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/instr/ikaruga_instructions.pdf',
        filesUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/svg/ikaruga_svg.zip',
        size: 'rozpětí 300 mm',
        stock: 9
    },
    {
        id: 'star-005',
        name: 'Snowspeeder Wooden Kit',
        category: 'starfighters',
        description: 'Snowspeeder optimalizovaný pro dřevěné díly. V balíčku jsou připravené SVG vrstvy.',
        price: 890,
        tokens: 8900,
        oldPrice: null,
        image: './img/starfighters/snowspeeder.png',
        badge: 'Hoth Spec',
        inStock: false,
        modelUrl: './models/snowspeeder.stl',
        instructionsUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/instr/snowspeeder_instructions.pdf',
        filesUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/svg/snowspeeder_svg.zip',
        size: 'rozpětí 300 mm',
        stock: 11
    },
    {
        id: 'star-006',
        name: 'TIE Fighter Wooden Kit',
        category: 'starfighters',
        description: 'Precizní TIE Fighter. Přiložený STL náhled umožní kontrolu proporcí.',
        price: 790,
        tokens: 7900,
        oldPrice: 1490,
        image: './img/starfighters/tiefighter.png',
        badge: 'Imperial',
        inStock: false,
        modelUrl: './models/tiefighter.stl',
        instructionsUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/instr/tiefighter_instructions.pdf',
        filesUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/svg/tiefighter_svg.zip',
        size: 'rozpětí 300 mm',
        stock: 16
    },
    {
        id: 'star-007',
        name: 'TIE Interceptor Wooden Kit',
        category: 'starfighters',
        description: 'Interceptor se štíhlými křídly. Připraven pro přesnou laserovou výrobu + PDF instrukce.',
        price: 790,
        tokens: 7900,
        oldPrice: null,
        image: './img/starfighters/tieinterceptor.png',
        badge: 'Limited',
        inStock: false,
        modelUrl: './models/tieinterceptor.stl',
        instructionsUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/instr/tieinterceptor_instructions.pdf',
        filesUrl: 'https://raw.githubusercontent.com/handpanda/wooden-starfighter/master/svg/tieinterceptor_svg.zip',
        size: 'rozpětí 300 mm',
        stock: 10
    },
    {
        id: 'star-008',
        name: 'Millennium Falcon Wooden Kit',
        category: 'starfighters',
        description: 'Ikonický Millennium Falcon ve dřevěném provedení. Kompletní stavebnice s detailním STL náhledem a PDF instrukcemi pro přesnou montáž.',
        price: 1490,
        tokens: 14900,
        oldPrice: 2490,
        image: './img2/falcon.jpeg',
        badge: 'Legendary',
        inStock: false,
        modelUrl: 'https://www.thingiverse.com/thing:919475',
        instructionsUrl: 'https://www.instructables.com/Laser-Cut-Millennium-Falcon/',
        filesUrl: 'https://www.thingiverse.com/thing:919475/files',
        size: 'rozpětí 400 mm',
        stock: 8
    },

    // === GRAVÍROVÁNÍ ===
    {
        id: 'engr-001',
        name: 'Gravírování loga - dřevo',
        category: 'engraving',
        description: 'Laserové gravírování vašeho loga nebo textu. Cena za plochu max 40x40 cm.',
        price: 490,
        tokens: 4900,
        oldPrice: null,
        image: './img/logo.jpg',
        badge: 'Služba',
        inStock: false,
        size: 'max 40×40 cm',
        stock: 25
    },
    {
        id: 'engr-002',
        name: 'Gravírovaná fotka na dřevo',
        category: 'engraving',
        description: 'Vaše fotografie přenesená laserem na dřevěnou destičku max 40x40 cm.',
        price: 490,
        tokens: 4900,
        oldPrice: null,
        image: './img/Heart2012.jpg',
        badge: 'Personalizace',
        inStock: false,
        size: 'max 40×40,A3 cm',
        stock: 18
    },
    {
        id: 'engr-003',
        name: 'QR kód vizitka - dřevěná',
        category: 'engraving',
        description: 'Originální dřevěná vizitka s gravírovaným QR kódem na vaše kontakty.',
        price: 190,
        tokens: 1900,
        oldPrice: null,
        image: './img/logo.jpg',
        badge: 'Business',
        inStock: false,
        size: '10x5 cm, množství dle objednávky, sleva na počet',
        stock: 1000
    },

    // === MERCH ===
    /*
        id: 'merch-001',
        name: 'Tričko ZION Terra Nova',
        category: 'merch',
        description: 'Bavlněné tričko s potiskem ZION Terra Nova. Velikosti S-XXL. Černá.',
        price: 490,
        tokens: 490,
        oldPrice: null,
        image: './img2/Z.gif',
        badge: 'Nové',
        inStock: false,
        size: 'S-XXL',
        stock: 0
    },
    {
        id: 'merch-002',
        name: 'Mikina ®evoluZion',
        category: 'merch',
        description: 'Prémiová mikina s kapucí a vyšitým logem. 80% bavlna, 20% polyester.',
        price: 1290,
        tokens: 1290,
        oldPrice: 1490,
        image: './img/evoluzionlogo.jpg',
        badge: 'Sleva',
        inStock: false,
        size: 'S-XXL',
        stock: 0
    },
    {
        id: 'merch-003',
        name: 'Hrnek Kalačakra',
        category: 'merch',
        description: 'Keramický hrnek s motivem tibetské Kalačakry. 350 ml. Myčka OK.',
        price: 290,
        tokens: 290,
        oldPrice: null,
        image: './img/kalacakra1.png',
        badge: null,
        inStock: false,
        size: '350 ml',
        stock: 0
    },
    */

    // === KNIHY === (přesunuto do Amenti Library jako free download)

    // === DIGITÁLNÍ ===
    {
        id: 'digi-001',
        name: 'Web Development - konzultace',
        category: 'digital',
        description: 'Hodinová konzultace k vývoji webových stránek. React, Vue, WordPress.',
        price: 390,
        tokens: 900,
        oldPrice: null,
        image: './develop/img/dev.jpg',
        badge: 'Online',
        inStock: true,
        size: '60 min session',
        stock: 12
    },
    {
        id: 'digi-002',
        name: 'Firemní/Osobní web OnePage - komplet',
        category: 'digital',
        description: 'Kompletní tvorba firemního/Osobního webu včetně designu a nasazení.',
        price: 4900,
        tokens: 49000,
        oldPrice: null,
        image: './img/144Halls.jpg',
        badge: 'Projekt',
        inStock: true,
        size: 'OnePage delivery',
        stock: 5
    },
    {
        id: 'digi-003',
        name: 'eShop řešení',
        category: 'digital',
        description: 'Implementace e-shopu s platební bránou a Zásilkovnou. Bez měsíčních poplatků.',
        price: 29900,
        tokens: 299000,
        oldPrice: 35000,
        image: './img/lotos.jpg',
        badge: 'Sleva',
        inStock: false,
        size: 'Full install',
        stock: 3
    },
    {
        id: 'digi-004',
        name: 'Fullstack web application',
        category: 'digital',
        description: 'Kompletní vývoj webové aplikace na míru. Frontend, backend, databáze, nasazení.',
        price: 79000,
        tokens: 790000,
        oldPrice: 99000,
        image: './img/lotos.jpg',
        badge: 'Sleva',
        inStock: false,
        size: 'End-to-end build',
        stock: 2
    },

    // === MINING SOFTWARE ===
    {
        id: 'soft-001',
        name: 'Miner Pro Desktop',
        category: 'software',
        description: 'GUI desktop mining aplikace pro Win/Mac/Linux. Auto-tune optimalizace, multi-pool support, real-time dashboard, consciousness XP tracking.',
        price: 990,
        tokens: 9900,
        oldPrice: null,
        image: './img/miner-pro.jpg',
        badge: 'Bestseller',
        inStock: false,
        size: 'Digital download',
        stock: 999
    },
    {
        id: 'soft-002',
        name: 'DAO Pool License',
        category: 'software',
        description: 'ZION Pool server (Docker). Whitelabel dashboard, multi-algo support, consciousness mining game, 30 dní email support.',
        price: 9990,
        tokens: 99000,
        oldPrice: null,
        image: './img/pool-license.jpg',
        badge: 'Enterprise',
        inStock: false,
        size: 'Docker + Support',
        stock: 999
    },
    {
        id: 'soft-003',
        name: 'Zion Rtx 5060 Miner & Oasis Ready',
        category: 'software',
        description: 'First Zion mining rig with optimized hardware and software integration.',
        price: 26900,
        tokens: 269000,
        oldPrice: 49900,
        image: './img/farm-bundle.jpg',
        badge: 'Bundle',
        inStock: false,
        size: 'Complete Cpu/Gpu Rig',
        stock: 99
    }
];

// Kategorie pro překlady
const CATEGORY_NAMES = {
    'seeds': 'Seeds',
    'books': 'Books', // 'Knihy' pro češtinu
    'woodart': 'WoodArt',
    'engraving': 'Gravírování',
    'merch': 'Merch',
    'digital': 'Digitální',
    'starfighters': 'Starfighters',
    'software': 'Mining Software'
};
