FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Standalone output already includes everything needed to run.
# When rsyncing locally-built artifacts, dirs are `standalone` and `static`.
COPY standalone ./
COPY static ./.next/static
COPY public ./public

EXPOSE 3000

CMD ["node", "server.js"]
