import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
await page.goto('http://localhost:3000/l6-issobella', { waitUntil: 'networkidle', timeout: 120000 });
await page.waitForTimeout(1500);
await page.locator('text=modulární platforma').first().scrollIntoViewIfNeeded();
await page.waitForTimeout(9000);
await page.screenshot({ path: '/tmp/l6-final.png', timeout: 60000 });
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle', timeout: 120000 });
await page.waitForTimeout(3000);
await page.locator('text=Holographic Earth').first().scrollIntoViewIfNeeded().catch(()=>{});
await page.waitForTimeout(9000);
await page.screenshot({ path: '/tmp/home-final.png', timeout: 60000 });
await browser.close();
console.log('done');
