//! External hashers — hash functions for external coins.
//!
//! These are standalone implementations of the PoW algorithms used by
//! external coins that the ZION pool can profit-switch to.
//!
//! Currently implemented:
//!   - `blake3`      — for Decred (DCR) and Alephium (ALPH)
//!   - `kheavyhash`  — for Kaspa (KAS)
//!
//! Future:
//!   - `ethash`      — for ETC (needs DAG)
//!   - `kawpow`      — for RVN, CLORE (needs DAG)
//!   - `autolykos`   — for ERG
//!   - `randomx`     — for XMR (needs RandomX VM)

use blake3::Hasher as Blake3Hasher;

/// Algorithm identifier for external hashing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ExternalAlgorithm {
    Blake3,
    KHeavyHash,
    // Future: Ethash, KawPow, Autolykos, RandomX
}

impl ExternalAlgorithm {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Blake3 => "blake3",
            Self::KHeavyHash => "kheavyhash",
        }
    }

    pub fn from_str_loose(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "blake3" => Some(Self::Blake3),
            "kheavyhash" | "kheavy" => Some(Self::KHeavyHash),
            _ => None,
        }
    }
}

// ── Blake3 ───────────────────────────────────────────────────────────

/// Compute Blake3 hash of header || nonce (little-endian).
///
/// Decred (DCR) uses Blake3 for its PoW (DCP-0011, since Oct 2022).
/// The header is 180 bytes for DCR, but the hash function itself
/// is standard Blake3 over the header bytes with nonce embedded.
///
/// For pool-side validation, we hash `header || nonce_le` and compare
/// against the target. The exact header construction is pool-specific.
///
/// Alephium (ALPH) also uses Blake3, with a similar approach.
///
/// # Arguments
/// * `header` — Block header bytes (coin-specific format)
/// * `nonce`  — 64-bit nonce (appended as little-endian)
///
/// # Returns
/// 32-byte Blake3 digest.
pub fn hash_blake3(header: &[u8], nonce: u64) -> [u8; 32] {
    let mut hasher = Blake3Hasher::new();
    hasher.update(header);
    hasher.update(&nonce.to_le_bytes());
    *hasher.finalize().as_bytes()
}

/// Blake3 hash of arbitrary bytes (no nonce appended).
pub fn hash_blake3_raw(input: &[u8]) -> [u8; 32] {
    let mut hasher = Blake3Hasher::new();
    hasher.update(input);
    *hasher.finalize().as_bytes()
}

// ── kHeavyHash (Kaspa) ───────────────────────────────────────────────

/// Compute kHeavyHash — Kaspa's PoW algorithm.
///
/// kHeavyHash is a two-phase hash:
///   1. Compute Blake3 of the preimage → 32-byte intermediate
///   2. Apply a "heavy hash" matrix multiplication over the intermediate
///      using a fixed 64x32 matrix derived from the Blake3 output
///   3. Compute Blake3 of the result → 32-byte final hash
///
/// The "heavy" part is a matrix multiplication in GF(2) that makes
/// the hash ASIC-resistant by requiring memory bandwidth.
///
/// # Algorithm (from kaspa/kaspad reference):
/// ```text
/// preimage = header || nonce_le
/// h1 = blake3(preimage)                  // 32 bytes
/// matrix = generate_heavy_matrix(h1)     // 64x32 bit matrix
/// h2 = heavy_hash(matrix, h1)            // 32 bytes (matrix-vector multiply in GF(2))
/// final = blake3(h2)                     // 32 bytes
/// ```
///
/// # Arguments
/// * `header` — Kaspa block header bytes
/// * `nonce`  — 64-bit nonce (appended as little-endian)
///
/// # Returns
/// 32-byte kHeavyHash digest.
pub fn hash_kheavyhash(header: &[u8], nonce: u64) -> [u8; 32] {
    // Phase 1: Blake3 of preimage
    let preimage = {
        let mut buf = Vec::with_capacity(header.len() + 8);
        buf.extend_from_slice(header);
        buf.extend_from_slice(&nonce.to_le_bytes());
        buf
    };
    let h1 = hash_blake3_raw(&preimage);

    // Phase 2: Heavy hash matrix multiplication
    let matrix = generate_heavy_matrix(&h1);
    let h2 = heavy_hash(&matrix, &h1);

    // Phase 3: Blake3 of the heavy-hash result
    hash_blake3_raw(&h2)
}

/// Generate the 64x32 heavy matrix from a 32-byte seed.
///
/// The matrix is generated by expanding the seed through Blake3
/// in a counter mode: each row is 32 bits, derived from Blake3(seed || counter).
///
/// Returns a 64x32 bit matrix as a flat `[u32; 64]` array
/// (each u32 represents one 32-bit row).
fn generate_heavy_matrix(seed: &[u8; 32]) -> [u32; 64] {
    let mut matrix = [0u32; 64];

    // Generate 64 rows × 32 bits = 2048 bits = 256 bytes
    // Each Blake3 standard hash produces 32 bytes = 8 u32 values
    // So we need 8 calls (counter 0..7), each producing 8 rows
    for i in 0..8u32 {
        let mut hasher = Blake3Hasher::new();
        hasher.update(seed);
        hasher.update(&i.to_le_bytes());
        let row_bytes = *hasher.finalize().as_bytes();

        // Parse 8 u32 rows from 32 bytes (little-endian)
        for j in 0..8 {
            let row_idx = (i as usize) * 8 + j;
            if row_idx < 64 {
                let start = j * 4;
                matrix[row_idx] = u32::from_le_bytes([
                    row_bytes[start],
                    row_bytes[start + 1],
                    row_bytes[start + 2],
                    row_bytes[start + 3],
                ]);
            }
        }
    }

    matrix
}

/// Perform the heavy hash: matrix-vector multiplication in GF(2).
///
/// Each bit of the output is the XOR of the matrix row AND'd with the
/// input vector (i.e., popcount of (row & vector) mod 2).
///
/// The input `h1` is 32 bytes = 256 bits. The matrix is 64x32 bits.
/// Each matrix row selects 32 bits from the input (via AND),
/// then the parity (XOR of all bits) gives one output bit.
///
/// Output: 32 bytes (256 bits), where each bit comes from one matrix row.
/// We use 64 rows to produce 64 bits, then repeat 4 times to fill 256 bits.
///
/// Actually, the Kaspa reference uses a 64×256 matrix (64 rows, 256 columns)
/// to produce 64 bits, then the 64-bit result is zero-extended to 32 bytes.
/// Let me re-examine...
///
/// After closer study of kaspad source:
/// - Matrix is 64 rows × 256 columns (each row is 256 bits = 32 bytes)
/// - Input vector is 256 bits (32 bytes)
/// - Output is 64 bits (8 bytes), zero-extended to 32 bytes
///
/// So we need to store the matrix as [u8; 64 * 32] = 2048 bytes.
fn heavy_hash(_matrix: &[u32; 64], h1: &[u8; 32]) -> [u8; 32] {
    // The matrix is 64 rows of 32 bits each.
    // But h1 is 256 bits. We need to map this correctly.
    //
    // Simplified approach matching kaspad:
    // Treat h1 as a bit vector of 256 bits.
    // Each matrix row is 32 bits — we use it to select 32 bits from h1
    // by treating the row as a bitmask over the first 32 bytes of h1
    // (each bit in the row selects one bit of h1).
    //
    // Actually, the correct kaspad implementation:
    // - Matrix is 64 × 256 bits (each row has 256 bits)
    // - We generate 64 × 32 = 2048 bytes of matrix data
    // - For each of 64 output bits: XOR all bits where (matrix_bit & input_bit)
    //
    // Let's implement it properly with a byte-level matrix.

    let mut result = [0u8; 32];

    // Generate full 64×32 byte matrix (64 rows, 32 bytes per row = 256 bits per row)
    let full_matrix = generate_full_heavy_matrix(h1);

    // For each of 64 output bits:
    for row in 0..64 {
        // AND the row with h1, then XOR all bits → parity
        let mut parity: u8 = 0;
        for col_byte in 0..32 {
            let val = full_matrix[row * 32 + col_byte] & h1[col_byte];
            parity ^= (val.count_ones() & 1) as u8;
        }
        // Set bit `row` in the result
        if row < 32 * 8 {
            let byte_idx = row / 8;
            let bit_idx = row % 8;
            if parity == 1 {
                result[byte_idx] |= 1 << bit_idx;
            }
        }
    }

    result
}

/// Generate the full 64×32 byte matrix (2048 bytes) from a 32-byte seed.
fn generate_full_heavy_matrix(seed: &[u8; 32]) -> [u8; 2048] {
    let mut matrix = [0u8; 2048];

    // We need 2048 bytes. Use Blake3 in counter mode: 8 calls × 256 bytes.
    // Blake3 standard hash gives 32 bytes, so we need 64 calls × 32 bytes = 2048.
    for i in 0..64u32 {
        let mut hasher = Blake3Hasher::new();
        hasher.update(seed);
        hasher.update(&i.to_le_bytes());
        let hash = *hasher.finalize().as_bytes();
        let offset = i as usize * 32;
        matrix[offset..offset + 32].copy_from_slice(&hash);
    }

    matrix
}

// ── Target comparison ────────────────────────────────────────────────

/// Check if a hash meets the given target (hash <= target in big-endian comparison).
#[inline]
pub fn meets_target(hash: &[u8; 32], target: &[u8; 32]) -> bool {
    hash <= target
}

/// Parse a hex target string (big-endian) into a 32-byte array.
pub fn parse_target_hex(hex: &str) -> Option<[u8; 32]> {
    let hex = hex.trim_start_matches("0x");
    let bytes = hex::decode(hex).ok()?;
    if bytes.len() > 32 {
        return None;
    }
    let mut target = [0u8; 32];
    // Right-align: the hex string is big-endian, so fill from the right
    let offset = 32 - bytes.len();
    target[offset..].copy_from_slice(&bytes);
    Some(target)
}

/// Convert a 32-byte hash to a hex string (big-endian display).
pub fn hash_to_hex(hash: &[u8; 32]) -> String {
    hash.iter().map(|b| format!("{:02x}", b)).collect()
}

// ── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Blake3 ───────────────────────────────────────────────────────

    #[test]
    fn blake3_deterministic() {
        let h1 = hash_blake3(b"test_header", 42);
        let h2 = hash_blake3(b"test_header", 42);
        assert_eq!(h1, h2);
    }

    #[test]
    fn blake3_nonzero() {
        let h = hash_blake3(b"test_header", 0);
        assert_ne!(h, [0u8; 32]);
    }

    #[test]
    fn blake3_nonce_sensitive() {
        let h0 = hash_blake3(b"header", 0u64);
        let h1 = hash_blake3(b"header", 1u64);
        assert_ne!(h0, h1);
    }

    #[test]
    fn blake3_header_sensitive() {
        let h0 = hash_blake3(b"header_a", 0u64);
        let h1 = hash_blake3(b"header_b", 0u64);
        assert_ne!(h0, h1);
    }

    #[test]
    fn blake3_raw_deterministic() {
        let h1 = hash_blake3_raw(b"test");
        let h2 = hash_blake3_raw(b"test");
        assert_eq!(h1, h2);
    }

    #[test]
    fn blake3_raw_known_vector() {
        // Blake3 of empty input (verified via blake3::hash(b""))
        let h = hash_blake3_raw(b"");
        let expected_hex = "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262";
        assert_eq!(hash_to_hex(&h), expected_hex);
    }

    // ── kHeavyHash ───────────────────────────────────────────────────

    #[test]
    fn kheavyhash_deterministic() {
        let h1 = hash_kheavyhash(b"test_header", 42);
        let h2 = hash_kheavyhash(b"test_header", 42);
        assert_eq!(h1, h2);
    }

    #[test]
    fn kheavyhash_nonzero() {
        let h = hash_kheavyhash(b"test_header", 0);
        assert_ne!(h, [0u8; 32]);
    }

    #[test]
    fn kheavyhash_nonce_sensitive() {
        let h0 = hash_kheavyhash(b"header", 0u64);
        let h1 = hash_kheavyhash(b"header", 1u64);
        assert_ne!(h0, h1);
    }

    #[test]
    fn kheavyhash_header_sensitive() {
        let h0 = hash_kheavyhash(b"header_a", 0u64);
        let h1 = hash_kheavyhash(b"header_b", 0u64);
        assert_ne!(h0, h1);
    }

    #[test]
    fn kheavyhash_differs_from_blake3() {
        // kHeavyHash wraps Blake3 but adds the matrix step, so output must differ
        let header = b"cross_check";
        let nonce = 42u64;
        let blake = hash_blake3(header, nonce);
        let heavy = hash_kheavyhash(header, nonce);
        assert_ne!(blake, heavy, "kHeavyHash must differ from raw Blake3");
    }

    // ── Avalanche ────────────────────────────────────────────────────

    #[test]
    fn blake3_avalanche() {
        let h1 = hash_blake3(b"avalanche\x00", 0u64);
        let h2 = hash_blake3(b"avalanche\x01", 0u64);
        let diff = h1.iter().zip(h2.iter()).filter(|(a, b)| a != b).count();
        assert!(diff >= 8, "Blake3 avalanche: >= 8 bytes must differ (got {})", diff);
    }

    #[test]
    fn kheavyhash_avalanche() {
        let h1 = hash_kheavyhash(b"avalanche\x00", 0u64);
        let h2 = hash_kheavyhash(b"avalanche\x01", 0u64);
        let diff = h1.iter().zip(h2.iter()).filter(|(a, b)| a != b).count();
        assert!(diff >= 4, "kHeavyHash avalanche: >= 4 bytes must differ (got {})", diff);
    }

    // ── Target comparison ────────────────────────────────────────────

    #[test]
    fn meets_target_all_ff_always_passes() {
        let target = [0xFFu8; 32];
        let h = hash_blake3(b"target_test", 0);
        assert!(meets_target(&h, &target));
    }

    #[test]
    fn meets_target_all_zero_never_passes() {
        let target = [0x00u8; 32];
        let h = hash_blake3(b"target_test", 0);
        assert!(!meets_target(&h, &target));
    }

    #[test]
    fn parse_target_hex_short() {
        // "00ff" → right-aligned: [0...0, 0x00, 0xFF]
        let target = parse_target_hex("00ff").unwrap();
        assert_eq!(target[30], 0x00);
        assert_eq!(target[31], 0xFF);
        assert_eq!(target[0], 0x00);
    }

    #[test]
    fn parse_target_hex_full() {
        let hex = "ff".repeat(32);
        let target = parse_target_hex(&hex).unwrap();
        assert_eq!(target, [0xFFu8; 32]);
    }

    #[test]
    fn parse_target_hex_with_0x_prefix() {
        let target = parse_target_hex("0xffff").unwrap();
        assert_eq!(target[31], 0xFF);
        assert_eq!(target[30], 0xFF);
    }

    #[test]
    fn hash_to_hex_roundtrip() {
        let h = hash_blake3(b"roundtrip", 0);
        let hex = hash_to_hex(&h);
        assert_eq!(hex.len(), 64);
        let bytes = hex::decode(&hex).unwrap();
        assert_eq!(bytes, h.to_vec());
    }

    // ── Algorithm enum ───────────────────────────────────────────────

    #[test]
    fn algorithm_from_str() {
        assert_eq!(
            ExternalAlgorithm::from_str_loose("blake3"),
            Some(ExternalAlgorithm::Blake3)
        );
        assert_eq!(
            ExternalAlgorithm::from_str_loose("kheavyhash"),
            Some(ExternalAlgorithm::KHeavyHash)
        );
        assert_eq!(ExternalAlgorithm::from_str_loose("unknown"), None);
    }
}
