#!/bin/bash
SCRIPT_DIR=$(cd $(dirname $0) && pwd)
export ZION_GPU_BACKEND=${ZION_GPU_BACKEND:-opencl}
export ZION_GPU_WORK_SIZE=${ZION_GPU_WORK_SIZE:-64}
export ZION_OCL_VRAM_PCT=${ZION_OCL_VRAM_PCT:-25}
export ZION_OCL_LOCAL_SIZE=${ZION_OCL_LOCAL_SIZE:-64}
export ZION_VERBOSE=${ZION_VERBOSE:-1}
export ZION_READ_TIMEOUT_SECS=${ZION_READ_TIMEOUT_SECS:-120}
echo "[wrapper] v3.0.4 GPU_BACKEND=$ZION_GPU_BACKEND WORK=$ZION_GPU_WORK_SIZE LWS=$ZION_OCL_LOCAL_SIZE"
exec ${SCRIPT_DIR}/zion-miner-bin "$@"
