#!/usr/bin/env bash
# ZION V3 — Start Prometheus + Grafana via Docker Compose (Linux/macOS)
set -uo pipefail
source "$(dirname "$0")/_lib.sh"

COMPOSE_FILE="$REPO_ROOT/V3/docker/docker-compose.yml"
ENV_FILE="$REPO_ROOT/V3/docker/.env"

zlog "ZION V3 Monitoring Stack (Prometheus + Grafana)"

if ! command -v docker >/dev/null 2>&1 || ! docker version >/dev/null 2>&1; then
    zlog "[ERROR] Docker is not available or not running. Start Docker and retry."
    exit 1
fi

if [[ ! -f "$ENV_FILE" ]]; then
    zlog "[WARN] $ENV_FILE not found. Creating minimal default (Grafana password: zionadmin)."
    printf '# Auto-generated by start-monitoring.sh\nGF_SECURITY_ADMIN_PASSWORD=zionadmin\n' > "$ENV_FILE"
fi

zlog "Starting Prometheus and Grafana..."
( cd "$(dirname "$COMPOSE_FILE")" && docker compose -f "$COMPOSE_FILE" --profile monitoring up -d ) || {
    zlog "[ERROR] docker compose failed."
    exit 1
}

zlog "Monitoring stack started."
zlog "  Prometheus : http://127.0.0.1:9090"
zlog "  Grafana    : http://127.0.0.1:3000 (login: admin / see V3/docker/.env)"
