# ZION V3 — Start Prometheus + Grafana via Docker Compose
# Uses V3/docker/docker-compose.yml with the 'monitoring' profile.

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Definition)
$ComposeFile = Join-Path $RepoRoot "V3\docker\docker-compose.yml"
$EnvFile = Join-Path $RepoRoot "V3\docker\.env"

Write-Host "ZION V3 Monitoring Stack (Prometheus + Grafana)" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan

# Check Docker
$dockerOk = $false
try {
    $null = docker version 2>$null
    $dockerOk = $LASTEXITCODE -eq 0
} catch {}

if (-not $dockerOk) {
    Write-Host "[ERROR] Docker is not available or not running." -ForegroundColor Red
    Write-Host "        Please start Docker Desktop and try again." -ForegroundColor Yellow
    exit 1
}

# Ensure .env exists (Grafana needs admin password)
if (-not (Test-Path $EnvFile)) {
    Write-Host "[WARN] $EnvFile not found. Creating minimal default..." -ForegroundColor Yellow
    $defaultEnv = @"
# Auto-generated by start-monitoring.ps1
GF_SECURITY_ADMIN_PASSWORD=zionadmin
"@
    $defaultEnv | Out-File -FilePath $EnvFile -Encoding UTF8
    Write-Host "      Default Grafana password: zionadmin" -ForegroundColor Yellow
    Write-Host "      Edit $EnvFile to change it." -ForegroundColor Yellow
}

# Launch Prometheus + Grafana
Write-Host ""
Write-Host "Starting Prometheus and Grafana..." -ForegroundColor Cyan
Push-Location (Split-Path $ComposeFile -Parent)
try {
    docker compose -f $ComposeFile --profile monitoring up -d
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] docker compose failed." -ForegroundColor Red
        exit 1
    }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "Monitoring stack started!" -ForegroundColor Green
Write-Host "  Prometheus : http://127.0.0.1:9090"  -ForegroundColor White
Write-Host "  Grafana    : http://127.0.0.1:3000  (login: admin / see V3/docker/.env)" -ForegroundColor White
Write-Host ""
Write-Host "To stop:  scripts\stop-monitoring.ps1" -ForegroundColor Gray
