export const SITE_VERSION = 'v2.9.9';
export const SITE_RELEASE_NAME = 'Pure Code';
export const SITE_RELEASE_LABEL = `${SITE_VERSION} \"${SITE_RELEASE_NAME}\"`;
export const SITE_RUNTIME_VERSION = 'v2.9.8';
export const SITE_RUNTIME_NAME = 'Deeksha/Ekam canonical';
export const SITE_RUNTIME_LABEL = `${SITE_RUNTIME_VERSION} ${SITE_RUNTIME_NAME}`;
export const SITE_ENVIRONMENT_LABEL = 'V3 Mainnet';
export const SITE_PUBLIC_LAUNCH_STATUS = 'Launch Countdown';
export const SITE_LAUNCH_DATE = '2026-06-20T00:00:00Z';
export const SITE_LAUNCH_DATE_DISPLAY = '20 June 2026';
export const SITE_NETWORK_LABEL = `${SITE_ENVIRONMENT_LABEL} · ${SITE_RELEASE_LABEL}`;
export const SITE_PRIMARY_HOST = '91.98.122.165';
export const SITE_PRIMARY_RPC_PORT = 8443;
export const SITE_PRIMARY_RPC_URL = `${SITE_PRIMARY_HOST}:${SITE_PRIMARY_RPC_PORT}`;
export const SITE_PRIMARY_POOL_API_URL = `http://${SITE_PRIMARY_HOST}:8080`;
export const SITE_PRIMARY_DAO_API_URL = `http://${SITE_PRIMARY_HOST}:8081`;
export const SITE_NETWORK_TOPOLOGY = '3-node test-mainnet rehearsal · Prague + USA + Singapore';
export const SITE_POOL_PRIMARY = `${SITE_PRIMARY_HOST}:3333`;
export const EKAM_GOLDEN_EGG_IMAGE = 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2147915250/settings_images/8802b3-c826-05c7-bcd2-12b608d18d1_ABOUT-ONENESS.webp';
export const EKAM_BANNER_IMAGE = 'https://onenessoceania.org/wp-content/uploads/2024/04/Ekam-Banner.jpg';
export const EKAM_FOUNDERS_BANNER_IMAGE = 'https://onenessoceania.org/wp-content/uploads/2024/03/Sri-Amma-Bhagavan-1920x600-1.jpg';
export const EKAM_SOURCE_URL = 'https://www.theonenessmovement.org/about-oneness';

/* ── Ekam extended image gallery ── */
export const EKAM_PREETHAJI_KRISHNAJI_IMAGE = 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2147915250/settings_images/18b2aa8-d063-5aa1-0e7-145623a46531_a2012e18-e98c-4e65-8212-ff2823f727ae.png';
export const EKAM_NORDIC_IMAGE = 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2147915250/settings_images/831114-c24e-e4a-5a4a-d84434bb22c_ot.jpeg';
export const EKAM_TURIYA_IMAGE = 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2147915250/settings_images/0ea3f2-e65e-3cc-3cca-e6f67bd6e7cc_TheOnenessTuriya_Intorior-Page_V5_07.jpg';
export const EKAM_PREETHAJI_KRISHNAJI_URL = 'https://www.theonenessmovement.org/sri-preethaji-and-sri-krishnaji';
export const EKAM_YOUTUBE_CHANNEL = 'https://www.youtube.com/@theonenessmovement';
