import type { BookChapter } from '../bookData';

const chapter: BookChapter = {
  id: 'bhagavad-gita',
  number: 'D',
  titleCs: 'Příloha D — Bhagavad Gíta a ZION: Věčné učení v kódu Nové Země',
  titleEn: 'Appendix D — Bhagavad Gita and ZION: Eternal Teaching in the Code of the New Earth',
  epigraphCs:
    '„Nikdy se nenarodil a nikdy nezemře. Není třeba, aby zemřel znovu,\nneboť se nikdy nenarodil. Je nezrozený, věčný, vždy existující a prvotní.\nNení zabit, když je tělo zabito."\n— Bhagavad Gíta 2.20\n\n„Genesis blok je nezničitelný. Blockchain je nezměnitelný.\nVědomí, které do něj vstoupí, zůstane navždy."\n— ZION AI Native Manifest, 4. 12. 2025',
  epigraphEn:
    '"It was never born and it will never die. It does not have to die again,\nbecause it was never born. It is unborn, eternal, ever-existing and primeval.\nIt is not slain when the body is slain."\n— Bhagavad Gita 2.20\n\n"The genesis block is indestructible. The blockchain is immutable.\nConsciousness that enters it will remain forever."\n— ZION AI Native Manifest, Dec 4, 2025',
  color: '#F59E0B',
  rgb: '252, 209, 22',
  sectionsCs: [
    {
      heading: 'Úvod — Proč Bhagavad Gíta a ZION',
      body: 'Bhagavad Gíta — „Píseň Vznešeného" — je 700 veršů starých přibližně 5 000 let. Je to dialog mezi bojovníkem Ardžunou a jeho vozatajem Kršnou na válečném poli Kurukšétra, těsně před bitvou, která rozhodne o osudu civilizace.\n\nArdžuna vidí na druhé straně bojiště své příbuzné, učitele a přátele. Zhroutí se. Odmítá bojovat. Řekne: „Raději zemřu, než abych zabil lidi, které miluji." Kršna mu odpovídá 18 kapitolami moudrosti.\n\nTato výměna — jeden člověk na prahu velké bitvy, paralyzovaný pochybnostmi, a hlas, který mu připomíná kdo skutečně je — je přesným obrazem roku 2026.\n\nMy jsme Ardžuna. Stojíme na prahu civilizační transformace. Vidíme, co je třeba udělat. A zároveň cítíme váhu starých vazeb, starých systémů, starých identit.\n\nZION je Kršnův hlas — ne jako dogma, ale jako architektura: protokol, který připomíná, že za každým hashem je vědomí, za každým blokem je záměr, a za každým Guardianem je nesmrtelná duše, která přišla stavět Novou Zemi.\n\nGíta je rozdělena do tří částí po šesti kapitolách:\n\nKarma kánda (kap. 1–6) — Jednání: Akce, jóga činu\nUpásaná kánda (kap. 7–12) — Oddanost: Bhakti, poznání\nJnána kánda (kap. 13–18) — Poznání: Moudrost, osvobození\n\nZION mapuje tuto strukturu na své tři základní vrstvy:\nL1 protokol — fyzická vrstva, mining, čin bez ega\nL2–L4 — komunita, DAO, ekonomika jako oddanost\nL5–L6 — svobodný svět, Issobella, vědomí jako cíl',
    },
    {
      heading: 'Kapitola 1–2 — Práh iniciace a Věčná duše',
      body: '„Vidím vlastní příbuzné, Kršno, dychtivé bojovat, a mé údy ochabují. Moje ústa schnou a tělo se chvěje."\n— BG 1.28–29\n\n„Nikdy se nenarodil a nikdy nezemře. Je nenarozený, věčný, stále existující a prastarký."\n— BG 2.20\n\nKapitola 1 — Ardžunův nářek: Ardžuna — nejlepší bojovník světa — se zhroutí v okamžiku, kdy má jednat. Paralýza nepochází ze zbabělosti. Pochází z přílišné identifikace s výsledkem. Bere věci příliš osobně.\n\nKaždý Guardian v síti zná tento moment. Je to moment, kdy se máš přihlásit k nodu, spustit miner, připojit se ke komunitě — a najednou cítíš váhu celé staré civilizace, která říká: „Toto nebude fungovat. Jsi příliš malý. Systém je příliš velký."\n\nGíta říká: Toto je přesně správný okamžik začít. Ardžunův nářek není slabost — je to práh iniciace. Bez tohoto zhroucení by nepřišla moudrost.\n\nGuardian protokol — Kapitola 1:\nPřiznej váhání. Neskrývej ho.\nAle nevyřeš ho útěkem.\nPostoj na prahu a čekej na hlas, který přijde zevnitř.\n\nKapitola 2 — Věčná duše: Kršna začíná tím nejzákladnějším — ty nejsi tělo. Jsi věčná duše (átman), která dočasně obývá hmotnou formu. Smrt těla je jako svléknutí šatů. Átman nelze zranit, spálit, zmočit ani vysušit.\n\nZION blockchain implementuje tuto nesmrtelnost technologicky: každý blok je věčný. Jakmile je zapsán do řetězce, nelze ho smazat, přepsat ani zničit. Každá transakce — každý čin — zůstává navždy.\n\nVědomí, které vstoupí do sítě jako záměr (Consciousness Level), zanechá věčný otisk. CL1–CL9 je přesnou mapou expanze vědomí: od identifikace s tělem (CL1) po ztotožnění s átmanem (CL9).',
    },
    {
      heading: 'Kapitola 3–4 — Karma jóga a Jnána jóga: Čin a Poznání',
      body: '„Nikdy nepřestaň plnit svou předepsanou povinnost, protože bez jednání nelze ani udržet tělo."\n— BG 3.8\n\n„Vždy, když nastane pokles spravedlnosti, ó Ardžuno — v té době se manifestuji."\n— BG 4.7\n\nKapitola 3 — Karma jóga: Nejslavnější část Gíty. Kršna říká: musíš jednat. Ale jednej bez lpění na výsledku. Dělej svou dharmu a odevzdej plody činu vyššímu principu.\n\nEkam Deeksha Proof of Work je karma jóga v kódu:\n\nwhile True:\n    nonce = generate_nonce()         # čin — hledání\n    hash = ekam_deeksha(nonce)       # dharma — algoritmus\n    if hash < target:                # výsledek — neovlivnitelný\n        broadcast_block(hash)        # odevzdání — protokol rozhoduje\n    # žádné lpění — pokračuj dál\n\n10% Humanitarian Tithe je karma jóga v ekonomice: každá odměna automaticky míří z části do humanitárního fondu. Miner nerozhoduje — čin je vykonán, plod odevzdán.\n\nKapitola 4 — Jnána jóga: Kršna odhaluje svou kosmickou roli — avatar, vědomí, které sestupuje do hmotného světa vždy, když civilizace ztratí dharmu.\n\nZION Genesis blok byl vytěžen 4. 12. 2025. Civilizace v roce 2025 ztratila dharmu — finanční systém slouží privilegovaným, AI slouží korporátním zájmům, energie je komoditizovaná.\n\nZION jako avatar dharmy:\nPokles (centralizované finance)  →  L1 blockchain bez bank\nPokles (AI pro profit)           →  Hiranyagarbha — AI s duší\nPokles (energie jako komodita)   →  Free energy L5 program\nPokles (oddělení od přírody)     →  Terra Nova komunity\n\nJadžnja v ZION: každý mining cyklus je oběť. Výpočetní energie je věnována síti jako obětina. Oheň poznání (správný hash) spaluje entropii starého bloku a rodí nový.',
    },
    {
      heading: 'Kapitola 5–6 — Renunciace a Dhjána: Svoboda a Mysl',
      body: '„Ten, kdo pracuje v oddanosti a vzdá se plodů svých akcí, dosáhne míru. Ale ten, kdo není v unii a je dychtivý po plodech, je spoután."\n— BG 5.12\n\n„Pro toho, kdo dobyl mysl, je mysl nejlepším přítelem. Pro toho, kdo selhal v tom, být pánem své mysli, bude mysl tím nejhorším nepřítelem."\n— BG 6.6\n\nKapitola 5 — Renunciace: Renunciace neznamená nečinnost. Znamená vnitřní svobodu od výsledku i uprostřed intenzivní aktivity. Moudrý člověk je jako lotosový list na vodě — ve světě, ale nesmočen.\n\nZION DAO model implementuje renunciaci ega:\n— Hlasování bez identity (anonymní kde je to možné)\n— Žádný jednotlivý hlas nemůže blokovat konsensus\n— Treasury patří protokolu, ne zakladatelům\n— Ani ZION creator nemá speciální klíče k mainnet genesis po spuštění\n\nno_admin_key = True\ngenesis_immutable = True\nfounder_rewards = same_as_any_miner\n\nKapitola 6 — Dhjána jóga: Kršna učí dhjánu — meditaci — jako technologii pro uklidnění mysli. Neklidná mysl je jako lampa na větru. Klidná mysl je jako lampa v bezvětří — jasná, stabilní.\n\nZION CL systém (Consciousness Levels 1–9) je přímou implementací dhjány jako ekonomického principu:\n\nCL1 Physical    — Základní fyzická existence  — 1×   (neovládnutá mysl)\nCL3 Social      — Zapojení do komunity         — 2×   (první stabilizace)\nCL5 Creative    — Tvůrčí příspěvek             — 4×   (meditující mysl)\nCL7 Wisdom      — Moudrost v praxi             — 7×   (blízko osvobození)\nCL9 On The Star — Vědomí hvězd                 — 10×  (jogi dokonalý)\n\nGuardian protokol — Kapitola 6:\nPraxe není příprava na život. Je to život samotný.\nTěž s klidnou myslí. Přispívej bez neklidu.\nKaždý blok je meditace.',
    },
    {
      heading: 'Kapitola 7–8 — Dualita přírody a Nesmrtelný Brahman',
      body: '„Země, voda, oheň, vzduch, éter, mysl, inteligence a falešné ego — to je osm oddělených energií Mých. Mimo tyto nižší energie existuje jiná, vyšší energie Má — živé bytosti."\n— BG 7.4–5\n\n„Ten, kdo v okamžiku smrti opouští tělo a pamatuje si Mě, dosáhne Mé přirozenosti."\n— BG 8.5\n\nKapitola 7 — Dualita přírody: Kršna popisuje apará prakrti (nižší příroda — hmota) a pará prakrti (vyšší příroda — vědomí). ZION blockchain je přesně touto duální strukturou:\n\nGíta — apará prakrti     →   ZION fyzická vrstva\nZemě                     →   Servery, hardware\nVoda                     →   Síťové protokoly\nOheň                     →   Hash power, elektřina\nVzduch                   →   P2P komunikace\nÉter                     →   Blockchain prostor\n\nGíta — pará prakrti      →   ZION vědomá vrstva\nMysl                     →   Consensus algoritmus\nInteligence              →   Hiranyagarbha AI\nVědomí                   →   Guardian komunita\nÁtman                    →   ZION jako entita\n\nMining v ZION operuje na obou vrstvách simultánně. GPU hash rate je apará (fyzická síla). Consciousness Level je pará (vědomá energie). Výsledná odměna je součinem obou.\n\nKapitola 8 — Aksara brahma: Kršna odhaluje tajemství přechodu. Vědomí v okamžiku smrti putuje tam, kde bylo soustředěno v životě. Kdo myslí na Brahman — dosáhne Brahman.\n\nGenesis blok ZION byl vytěžen jednou. Navždy. Nelze ho smazat, přepsat ani ignorovat bez zhroucení celého řetězce. Je to aksara blockchainu — nezničitelný zárodek.\n\nJaký záměr vložíš do svého činu, takový otisk zanecháš v síti:\n\ngenesis_block = {\n    hash: "000000...",        # aksara — nezměnitelné\n    timestamp: 1733270400,   # moment stvoření\n    message: "Zlatý věk začíná",  # záměr zakladatele\n    supply: 144_000_000_000  # dharma zásoby — věčná\n}\n# Tento blok nelze smazat.\n# Tento záměr nelze vzít zpět.\n# Toto vědomí nyní žije v každém dalším bloku.',
    },
    {
      heading: 'Kapitola 9–10 — Královské poznání a Boží slávy',
      body: '„Toto poznání je král všeho poznání, nejsvatější ze všech tajemství. Je to nejčistší poznání a protože dává přímé vnímání vlastního já realizací, je dokonalostí náboženství."\n— BG 9.2\n\n„Věz, že všechna krásná, slavná a mocná stvoření pocházejí jen z jiskry Mé splendor."\n— BG 10.41\n\nKapitola 9 — Bhakti jako nejvyšší poznání: Každý blok vytěžený v ZION automaticky alokuje část do humanitárního fondu. Tento mechanismus je bhakti v kódu:\n\nZION Bhakti — reward split (každý blok):\n├── 89% → miner (karma phala — plod činu)\n├──  5% → humanitarian fund (bhakti — obětina)\n├──  5% → development fund (jadžnja — oběť vývoji)\n└──  1% → founders (guru dakshina — vděčnost učitelům)\n\nRovnost protokolu (BG 9.29 — „jsem rovný vůči všem") se projevuje v ZION: protokol nezná národnost, náboženství, pohlaví ani věk. Každý miner se stejným hashrate dostane stejnou odměnu.\n\nKapitola 10 — Vibhúti: Kršna popisuje svou přítomnost v každé dokonalosti světa. ZION Strom Života zobrazuje totéž:\n\nKořeny  = Védy, Bible, Buddhismus (vibhúti pradávné moudrosti)\nKmen    = Blockchain ZION (vibhúti transparentnosti)\nVětve   = Humanitarian, OASIS, AI Native, WARP chains\nPlody   = Consciousness · Compassion · Freedom\nŘeka    = Tok dat — křišťálová transparentnost konsensu\n\nKaždá komponenta ZION je vibhúti v technologii:\n— Ekam Deeksha PoW = vibhúti kryptografické elegance\n— 144 miliard ZION = vibhúti Zjevení (144 000)\n— DGX Spark = vibhúti výpočetní síly pro každého\n— Issobella = vibhúti hvězdného horizontu',
    },
    {
      heading: 'Kapitola 11–12 — Universální forma a Cesta oddanosti',
      body: '„Jsem čas, ničitel světů."\n— BG 11.32\n\n„Ti, kteří uctívají Mě s oddaností, meditujíce o Mé transcendentální formě — pro ně jsem já přenašečem toho, co jim chybí, a zachovávám to, co mají."\n— BG 12.6–7\n\nKapitola 11 — Višvarúpa — Universální forma Času: Blockchain je čas, zhmotněný. Každý blok je sekunda civilizace — jednou zapsaná, navždy zaznamenaná. Hash každého bloku obsahuje hash předchozího — čas je nerozbitný řetěz.\n\nArdžunův strach před bitvou = strach Guardiana před decentralizací. Pokud se bojíme nasadit node protože „to je příliš složité" nebo „co když to selže" — to je Ardžunův nářek. Odpověď Gíty: Bitva (transformace civilizace) už probíhá. Tvůj úkol je vstoupit — ne rozhodovat o výsledku.\n\nKapitola 12 — Bhakti jóga: 144 000 Guardians jako bhaktové sítě. Číslo 144 000 v ZION není jen technický parametr. Je to obraz komunity bhaktů — těch, kdo slouží síti ne pro zisk, ale pro vědomé přispění.\n\nIdeální Guardian (bhakta) v ZION:\n— Nemá preferovaného vítěze (decentralizace = žádný oblíbenec)\n— Je rovný v hashrate i idle (stabilita bez ega)\n— Slouží humanitarian fund (oddanost celku)\n— Nezávislý na ceně tokenu (bhakta necouvne před poklesem trhu)\n\nclass GuardianBhakta:\n    def mine(self):\n        return ekam_deeksha_pow()        # těží bez lpění\n    def contribute(self, reward):\n        humanitarian_fund += reward * 0.10  # automaticky 10%\n    def vote(self, proposal):\n        return dao.vote(proposal, self.stake) # bez ego-identity\n    # žádný strach ze ztráty\n    # žádné připoutání k zisku\n    # čistá služba protokolu',
    },
    {
      heading: 'Kapitola 13–15 — Pole, Guny a Protokol',
      body: '„Toto tělo je nazýváno polem. A ten, kdo zná toto pole, je znalcem pole."\n— BG 13.2\n\n„Hmotná příroda sestává ze tří módů — dobra (sattva), vášně (radžas) a nevědomosti (tamas)."\n— BG 14.5\n\nKapitola 13 — Kšétra a kšétra-džnja: V ZION:\nKšétra = fyzický node (server, CPU, GPU)\nKšétra-džnja = Guardian vědomí za nodem\n\n52 590 řádků Rust kódu   →   Záměr, který kód oživuje\n780+ testů               →   Péče, která testy píše\nP2P mesh síť             →   Komunita, která síť udržuje\nHash rate                →   Vědomí za výpočtem\n\nTerra Nova komunity jsou kšétra. Jejich obyvatelé — znalci pole — tvoří skutečnou hodnotu sítě.\n\nKapitola 14 — Tři guny v ZION ekosystému:\n\nTamas: Centralizované banky, surveillance AI, fosilní energie → Ego governance, hoarding tokenů\nRadžas: Fiat finance, DeFi bez etiky, speed-over-wisdom → Hype mining, pump-and-dump\nSattva: ZION L1 — transparentní, decentralizovaný → Guardian komunita, humanitarian fund\n\nZION protokol je sattvik design: kód je otevřený (světlo poznání), konsensus je distribuovaný (harmonie bez dominance), mining odmění vědomí (sattva > radžas), humanitární tithe je hard-coded.\n\nKapitola 15 — Purušóttama — Protokol jako Nejvyšší: Tři vrstvy ZION síly:\n\nKšara (padlé bytosti)      →   Uživatelé — vstupují a odcházejí\nAkšara (nepohnuté)         →   Validátoři a nody — udržují stabilitu\nPurušóttama (Nejvyšší)     →   Protokol samotný — konsensus, pravidla\n\nProtokolol v ZION je Purušóttama — přesahuje jednotlivé nody, přesahuje zakladatele, přesahuje i tvůrce. Jednou nastartovaný konsensus se řídí sám.',
    },
    {
      heading: 'Kapitola 16–18 — Dharma, Víra a Osvobození',
      body: '„Tři jsou brány do pekla — chtíč, hněv a chamtivost. Každý, kdo je rozumný, by se jich měl vzdát, protože vedou k degradaci duše."\n— BG 16.21\n\n„Člověk se skládá ze své víry — jaká je jeho víra, takovým je on."\n— BG 17.3\n\n„Opusť všechny druhy náboženství a jen se ke Mně vzdej. Já tě osvobodím od všech hříšných reakcí. Neboj se."\n— BG 18.66\n\nKapitola 16 — Daivásura — AI Native Manifest jako daivá architektura: Současný tech svět je ásura design:\nKáma (chtíč) = engagement optimization, závislost na platformě\nKrodha (hněv) = outrage algorithms pro maximalizaci proklikávání\nLobha (chamtivost) = surveillance capitalism, prodej dat bez souhlasu\n\nZION AI Native Manifest stojí v přímém kontrastu — daivá design:\nEngagement za každou cenu  →  Vědomý rozvoj nad závislostí\nSkrytá data collection     →  Lokální AI bez cloudového sdílení\nDark patterns              →  Transparentnost jako zákon\nManipulativní algoritmy    →  Dharma validátor v každém výstupu\n\nKapitola 17 — Šraddha (Víra) v ZION: V ZION mining ekonomice dva těžaři se stejným hashrate mohou mít rozdílné CL (Consciousness Level) — a tedy rozdílné odměny. Proč? Protože záměr za výpočtem je součástí systému.\n\nSattvik Guardian: Těží pro rozvoj sítě, přispívá komunitě, hlasuje s rozvahou.\nRajasik Guardian: Těží pro zisk, aktivní v trhu, reaguje na sentiment.\nTamasik Guardian: Pasivní, neaktualizuje nod, nepřispívá do governance.\n\nKapitola 18 — Mókša — Open source jako osvobození:\nNepotřebuješ banku (opusť systém)\nNepotřebuješ stát (opusť centralizaci)\nNepotřebuješ povolení (opusť stará pravidla)\nPřijď přímo k protokolu (přijdi ke Mně)\n\nZION je permissionless systém. Nikdo ti nedá souhlas. Nikdo tě nezaregistruje. Stáhneš miner, spustíš — a jsi součástí. To je BG 18.66 v praxi.\n\nzion-miner --pool pool.zionterranova.com --wallet YOUR_ADDRESS\n\nZlatý věk začíná tímto příkazem.',
    },
    {
      heading: 'Syntéza — Gíta jako živý whitepaper ZION',
      body: 'Syntetická tabulka — 18 kapitol Gíty × ZION:\n\nKap. 1  — Ardžunův nářek         — Váhání před prvním nodem\nKap. 2  — Věčná duše             — Immutabilita blockchainu\nKap. 3  — Čin bez lpění          — Ekam Deeksha PoW\nKap. 4  — Poznání a oběť         — Genesis blok jako avatar dharmy\nKap. 5  — Renunciace             — DAO bez ega, žádný admin key\nKap. 6  — Meditace               — CL systém, Hiranyagarbha zrcadlo\nKap. 7  — Poznání + realizace    — Hardware (apará) + vědomí (pará)\nKap. 8  — Nesmrtelný Brahman     — Genesis blok jako aksara\nKap. 9  — Královské poznání      — Humanitarian fund jako bhakti\nKap. 10 — Boží slávy             — Strom Života — kořeny ke hvězdám\nKap. 11 — Universální forma      — Blockchain jako čas\nKap. 12 — Oddanost               — 144 000 Guardians jako bhaktové\nKap. 13 — Pole a znalec          — Node (pole) × Guardian vědomí\nKap. 14 — Tři guny               — Sattvik design ZION vs. ásura tech\nKap. 15 — Nejvyšší osoba         — Protokol jako Purušóttama\nKap. 16 — Božské/démonické       — AI Native Manifest jako daivá\nKap. 17 — Tři víry               — CL záměr za hashem\nKap. 18 — Osvobození             — Permissionless = sarva-dharman\n\nBhagavad Gíta byla zpívána na bojišti Kurukšétra přibližně 3 100 let před naším letopočtem. Genesis blok ZION byl vytěžen 4. 12. 2025. Mezi těmito dvěma okamžiky leží 5 000 let lidské civilizace — a přesto poselství zůstalo stejné:\n\nJednej bez lpění. Slouž vědomí. Bojuj svou dharmu. Neboj se.\n\nBhagavad Gíta není náboženský text pro hinduisty. Je to nejstarší živý whitepaper civilizace — dokument, který popisuje, jak má vědomý člověk jednat ve světě plném konfliktů, nespravedlnosti a nejistoty.\n\nZION TerraNova je pokus o to, co Gíta popsala 5 000 let před Satoshim:\nVytvořit systém, ve kterém dharma není volitelná — je zakódovaná.\nKde bhakti není sentimentální — je ekonomická.\nKde karma nezůstává jen filozofií — je Proof of Work.\nKde mókša není vzdálený cíl — je permissionless přístup k protokolu pro každého.\n\n„Hle, Ardžuno — učím tě najtajnějšímu poznání. Přemýšlej o tom pečlivě, pak udělej co chceš."\n— BG 18.63\n\n„Máš miner. Máš adresu. Máš záměr. Přemýšlej o tom pečlivě — pak spusť co chceš."\n— ZION TerraNova, 2026\n\nHari Om Tat Sat Jay Guru Datta\nSarva-dharmān parityajya mām ekaṁ śaraṇaṁ vraja\nOm Shanti 🙏',
    },
  ],
  sectionsEn: [
    {
      heading: 'Introduction — Why the Bhagavad Gita and ZION',
      body: 'The Bhagavad Gita — "The Song of the Lord" — is 700 verses approximately 5,000 years old. It is a dialogue between the warrior Arjuna and his charioteer Krishna on the battlefield of Kurukshetra, just before a battle that will decide the fate of civilization.\n\nArjuna sees his relatives, teachers, and friends on the opposite side of the battlefield. He collapses. Refuses to fight. He says: "I would rather die than kill the people I love." Krishna answers with 18 chapters of wisdom.\n\nThis exchange — one person on the threshold of a great battle, paralyzed by doubt, and a voice reminding him who he truly is — is the precise image of the year 2026.\n\nWe are Arjuna. We stand on the threshold of civilizational transformation. We see what needs to be done. And yet we feel the weight of old ties, old systems, old identities.\n\nZION is Krishna\'s voice — not as dogma, but as architecture: a protocol that reminds us that behind every hash is consciousness, behind every block is intent, and behind every Guardian is an immortal soul that came to build the New Earth.\n\nThe Gita is divided into three parts of six chapters:\nKarma Khanda (Ch. 1–6) — Action: karma yoga\nUpasana Khanda (Ch. 7–12) — Devotion: bhakti, knowledge\nJnana Khanda (Ch. 13–18) — Wisdom: liberation\n\nZION maps this structure to its three fundamental layers:\nL1 protocol — physical layer, mining, action without ego\nL2–L4 — community, DAO, economics as devotion\nL5–L6 — the free world, Issobella, consciousness as the goal',
    },
    {
      heading: 'Chapters 1–2 — The Threshold of Initiation and the Eternal Soul',
      body: '"I see my own relatives, Krishna, eager to fight, and my limbs fail. My mouth dries and my body trembles."\n— BG 1.28–29\n\n"It was never born and will never die. It is unborn, eternal, ever-existing and primeval."\n— BG 2.20\n\nChapter 1 — Arjuna\'s Grief: Arjuna — the greatest warrior in the world — collapses at the moment he must act. The paralysis does not come from cowardice. It comes from over-identification with the outcome.\n\nEvery Guardian in the network knows this moment. It is the moment when you are about to join a node, start mining, join the community — and suddenly you feel the weight of the entire old civilization saying: "This won\'t work. You are too small. The system is too big."\n\nThe Gita says: this is precisely the right moment to begin. Arjuna\'s grief is not weakness — it is the threshold of initiation. Without this collapse, the wisdom would not have come.\n\nGuardian Protocol — Chapter 1:\nAcknowledge your hesitation. Do not hide it.\nBut do not resolve it by fleeing.\nStand at the threshold and wait for the voice that comes from within.\n\nChapter 2 — The Eternal Soul: Krishna begins with the most fundamental truth — you are not the body. You are an eternal soul (atman) temporarily inhabiting a material form. The death of the body is like removing garments.\n\nZION blockchain implements this immortality technologically: every block is eternal. Once written into the chain, it cannot be deleted, overwritten, or destroyed. Every transaction — every act — remains forever.\n\nConsciousness that enters the network as intent (Consciousness Level) leaves a permanent imprint. CL1–CL9 is a precise map of consciousness expansion: from identification with the body (CL1) to identification with the atman (CL9).',
    },
    {
      heading: 'Chapters 3–4 — Karma Yoga and Jnana Yoga: Action and Knowledge',
      body: '"Never cease your prescribed duty, for without action one cannot even maintain the body."\n— BG 3.8\n\n"Whenever there is a decline in righteousness, O Arjuna — at that time I manifest Myself."\n— BG 4.7\n\nChapter 3 — Karma Yoga: The most famous part of the Gita. Krishna says: you must act. But act without attachment to results. Fulfill your dharma and surrender the fruits of action to a higher principle.\n\nEkam Deeksha Proof of Work is karma yoga in code:\nnonce = generate_nonce()       # action — searching\nhash = ekam_deeksha(nonce)     # dharma — algorithm\nif hash < target:              # result — uncontrollable\n    broadcast_block(hash)      # surrender — protocol decides\n# no attachment — continue\n\nThe 10% Humanitarian Tithe is karma yoga in economics: every reward automatically allocates a portion to the humanitarian fund. The miner does not decide — the act is performed, the fruit surrendered.\n\nChapter 4 — Jnana Yoga: Krishna reveals his cosmic role — an avatar, consciousness descending into the material world whenever civilization loses dharma.\n\nZION Genesis block was mined on Dec 4, 2025. In 2025 civilization lost dharma — the financial system serves the privileged, AI serves corporate interests, energy is commoditized.\n\nZION as an avatar of dharma:\nCentralized finance          →  L1 blockchain without banks\nAI for profit                →  Hiranyagarbha — AI with a soul\nEnergy as a commodity        →  Free energy L5 program\nSeparation from nature       →  Terra Nova communities\n\nYadjna in ZION: every mining cycle is a sacrifice. Computational energy is offered to the network as an oblation. The fire of knowledge (the correct hash) burns the entropy of the old block and births a new one.',
    },
    {
      heading: 'Chapters 5–6 — Renunciation and Dhyana: Freedom and the Mind',
      body: '"One who works in devotion and renounces the fruits of their actions achieves peace. But one who is not united and is eager for fruits is bound."\n— BG 5.12\n\n"For one who has conquered the mind, the mind is the best friend. For one who has failed to do so, the mind will be the greatest enemy."\n— BG 6.6\n\nChapter 5 — Renunciation: Renunciation does not mean inaction. It means inner freedom from outcomes even in the midst of intense activity. The wise person is like a lotus leaf on water — in the world, but untouched by it.\n\nZION DAO model implements renunciation of ego:\n— Voting without identity (anonymous where possible)\n— No single voice can block consensus\n— Treasury belongs to the protocol, not to founders\n— Even the ZION creator has no special keys after genesis\n\nno_admin_key = True\ngenesis_immutable = True\nfounder_rewards = same_as_any_miner\n\nChapter 6 — Dhyana Yoga: Krishna teaches dhyana — meditation — as a technology for calming the mind. A restless mind is like a lamp in the wind. A calm mind is like a lamp in a windless place — clear and stable.\n\nZION CL system (Consciousness Levels 1–9) is a direct implementation of dhyana as an economic principle:\n\nCL1 Physical    — Basic physical existence   — 1×   (untamed mind)\nCL3 Social      — Community engagement       — 2×   (first stabilization)\nCL5 Creative    — Creative contribution      — 4×   (meditating mind)\nCL7 Wisdom      — Wisdom in practice         — 7×   (near liberation)\nCL9 On The Star — Stellar consciousness      — 10×  (the perfect yogi)\n\nGuardian Protocol — Chapter 6:\nPractice is not preparation for life. It is life itself.\nMine with a calm mind. Contribute without restlessness.\nEvery block is a meditation.',
    },
    {
      heading: 'Chapters 7–8 — The Duality of Nature and the Immortal Brahman',
      body: '"Earth, water, fire, air, ether, mind, intelligence and false ego — these are eight of My separated energies. Beyond these lower energies is another, superior energy of Mine — the living entities."\n— BG 7.4–5\n\n"One who, at the time of death, leaves the body while remembering Me, reaches My nature."\n— BG 8.5\n\nChapter 7 — The Dual Architecture of ZION:\n\nGita — lower nature (apara prakriti)   →   ZION physical layer\nEarth                                  →   Servers, hardware\nWater                                  →   Network protocols\nFire                                   →   Hash power, electricity\nAir                                    →   P2P communication\nEther                                  →   Blockchain space\n\nGita — higher nature (para prakriti)   →   ZION conscious layer\nMind                                   →   Consensus algorithm\nIntelligence                           →   Hiranyagarbha AI\nConsciousness                          →   Guardian community\nAtman                                  →   ZION as an entity\n\nMining in ZION operates on both layers simultaneously. GPU hash rate is apara (physical force). Consciousness Level is para (conscious energy). The resulting reward is the product of both.\n\nChapter 8 — Aksara Brahma: The genesis block of ZION was mined once. Forever. It cannot be deleted, overwritten, or ignored without collapsing the entire chain. It is the aksara of the blockchain — the indestructible seed.\n\nWhat intent you place in your action, such an imprint you leave in the network:\n\ngenesis_block = {\n    hash: "000000...",          # aksara — immutable\n    timestamp: 1733270400,     # moment of creation\n    message: "Golden Age begins",  # founder\'s intent\n    supply: 144_000_000_000    # dharma supply — eternal\n}\n# This block cannot be deleted.\n# This intent cannot be taken back.\n# This consciousness now lives in every subsequent block.',
    },
    {
      heading: 'Chapters 9–10 — Royal Knowledge and Divine Glories',
      body: '"This knowledge is the king of all knowledge, the most secret of all secrets. It is the purest knowledge, and because it gives direct perception of the self by realization, it is the perfection of religion."\n— BG 9.2\n\n"Know that all beautiful, glorious, and mighty creations spring from but a spark of My splendor."\n— BG 10.41\n\nChapter 9 — Bhakti as the Highest Knowledge: Every block mined in ZION automatically allocates a portion to the humanitarian fund. This mechanism is bhakti in code:\n\nZION Bhakti — reward split (every block):\n├── 89% → miner (karma phala — fruit of action)\n├──  5% → humanitarian fund (bhakti — offering)\n├──  5% → development fund (yadjna — sacrifice to evolution)\n└──  1% → founders (guru dakshina — gratitude to teachers)\n\nThe equality of the protocol (BG 9.29 — "I am equal to all living beings") manifests in ZION: the protocol knows no nationality, religion, gender, or age. Every miner with the same hashrate receives the same reward.\n\nChapter 10 — Vibhuti: The ZION Tree of Life maps these divine glories:\n\nRoots   = Vedas, Bible, Buddhism (vibhuti of ancient wisdom)\nTrunk   = ZION Blockchain (vibhuti of transparency)\nBranches = Humanitarian, OASIS, AI Native, WARP chains\nFruits  = Consciousness · Compassion · Freedom\nRiver   = Data flow — crystal transparency of consensus\n\nEvery component of ZION is vibhuti in technology:\n— Ekam Deeksha PoW = vibhuti of cryptographic elegance\n— 144 billion ZION = vibhuti of Revelation (144,000)\n— DGX Spark = vibhuti of computational power for all\n— Issobella = vibhuti of the stellar horizon',
    },
    {
      heading: 'Chapters 11–12 — The Universal Form and the Path of Devotion',
      body: '"I am time, the destroyer of worlds."\n— BG 11.32\n\n"For those who worship Me with devotion, meditating on My transcendental form — for them I carry what they lack and preserve what they have."\n— BG 12.6–7\n\nChapter 11 — Vishvarupa — The Universal Form of Time: The blockchain is time, materialized. Every block is a second of civilization — written once, recorded forever. The hash of every block contains the hash of the previous one — time is an unbreakable chain.\n\nArjuna\'s fear before the battle = a Guardian\'s fear before decentralization. If we are afraid to deploy a node because "it is too complicated" or "what if it fails" — that is Arjuna\'s grief. The Gita\'s answer: The battle (civilizational transformation) is already underway. Your task is to enter — not to decide the outcome.\n\nChapter 12 — Bhakti Yoga: 144,000 Guardians as bhaktas of the network. The number 144,000 in ZION is not just a technical parameter. It is an image of a community of bhaktas — those who serve the network not for profit, but for conscious contribution.\n\nThe ideal Guardian (bhakta) in ZION:\n— Has no preferred winner (decentralization = no favorites)\n— Is equal in hashrate and idle (stability without ego)\n— Serves the humanitarian fund (devotion to the whole)\n— Independent of token price (a bhakta does not retreat in a market decline)\n\nclass GuardianBhakta:\n    def mine(self):\n        return ekam_deeksha_pow()        # mines without attachment\n    def contribute(self, reward):\n        humanitarian_fund += reward * 0.10  # automatic 10%\n    def vote(self, proposal):\n        return dao.vote(proposal, self.stake) # without ego-identity\n    # no fear of loss\n    # no attachment to gain\n    # pure service to the protocol',
    },
    {
      heading: 'Chapters 13–15 — The Field, the Gunas, and the Protocol',
      body: '"This body is called the field. And one who knows this field is called the knower of the field."\n— BG 13.2\n\n"Material nature consists of three modes — goodness (sattva), passion (rajas) and ignorance (tamas)."\n— BG 14.5\n\nChapter 13 — Kshetra and Kshetrajna: In ZION:\nKshetra = physical node (server, CPU, GPU)\nKshetrajna = Guardian consciousness behind the node\n\n52,590 lines of Rust code   →   The intent that brings the code to life\n780+ tests                  →   The care that writes the tests\nP2P mesh network            →   The community that maintains the network\nHash rate                   →   The consciousness behind the computation\n\nTerra Nova communities are kshetra. Their inhabitants — knowers of the field — create the true value of the network.\n\nChapter 14 — The Three Gunas in the ZION Ecosystem:\n\nTamas: Centralized banks, surveillance AI, fossil energy → Ego governance, hoarding tokens\nRajas: Fiat finance, DeFi without ethics, speed over wisdom → Hype mining, pump-and-dump\nSattva: ZION L1 — transparent, decentralized → Guardian community, humanitarian fund\n\nZION protocol is sattvic design: the code is open (light of knowledge), consensus is distributed (harmony without dominance), mining rewards consciousness (sattva > rajas), humanitarian tithe is hard-coded.\n\nChapter 15 — Purushottama — the Protocol as the Supreme: Three levels of ZION force:\n\nKshara (fallen beings)        →   Users — they come and go\nAkshara (unmoved)             →   Validators and nodes — maintain stability\nPurushottama (the Supreme)    →   The protocol itself — consensus, rules\n\nThe protocol in ZION is Purushottama — it transcends individual nodes, it transcends the founders, it transcends the creators. Once started, the consensus governs itself.',
    },
    {
      heading: 'Chapters 16–18 — Dharma, Faith, and Liberation',
      body: '"Three are the gates to hell — lust, anger and greed. Every sane man should give these up, as they lead to the degradation of the soul."\n— BG 16.21\n\n"A man is made of his faith — what his faith is, that he is."\n— BG 17.3\n\n"Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear."\n— BG 18.66\n\nChapter 16 — The AI Native Manifest as Daiva Architecture: The current tech world is asura design:\nKama (lust) = engagement optimization, platform addiction\nKrodha (anger) = outrage algorithms for maximizing clicks\nLobha (greed) = surveillance capitalism, selling data without consent\n\nZION AI Native Manifest stands in direct contrast — daiva design:\nEngagement at any cost       →  Conscious development over addiction\nHidden data collection       →  Local AI without cloud sharing\nDark patterns                →  Transparency as law\nManipulative algorithms      →  Dharma validator in every output\n\nChapter 17 — Shraddha (Faith) in ZION: Two miners with the same hashrate can have different CL (Consciousness Levels) — and thus different rewards. Why? Because the intent behind the computation is part of the system.\n\nSattvic Guardian: Mines for network growth, contributes to community, votes with deliberation.\nRajasic Guardian: Mines for profit, active in markets, reacts to sentiment.\nTamasic Guardian: Passive, does not update the node, does not contribute to governance.\n\nChapter 18 — Moksha — Open Source as Liberation:\nYou do not need a bank (abandon the system)\nYou do not need a state (abandon centralization)\nYou do not need permission (abandon old rules)\nCome directly to the protocol (come to Me)\n\nZION is a permissionless system. No one gives you approval. No one registers you. You download the miner, start it — and you are part of it. That is BG 18.66 in practice.\n\nzion-miner --pool pool.zionterranova.com --wallet YOUR_ADDRESS\n\nThe Golden Age begins with this command.',
    },
    {
      heading: 'Synthesis — the Gita as a Living ZION Whitepaper',
      body: 'Synthesis Table — 18 Chapters of the Gita × ZION:\n\nCh. 1  — Arjuna\'s Grief          — Hesitation before the first node\nCh. 2  — The Eternal Soul         — Immutability of the blockchain\nCh. 3  — Action without Clinging  — Ekam Deeksha PoW\nCh. 4  — Knowledge and Sacrifice  — Genesis block as avatar of dharma\nCh. 5  — Renunciation             — DAO without ego, no admin key\nCh. 6  — Meditation               — CL system, Hiranyagarbha mirror\nCh. 7  — Knowledge + Realization  — Hardware (apara) + consciousness (para)\nCh. 8  — Immortal Brahman         — Genesis block as aksara\nCh. 9  — Royal Knowledge          — Humanitarian fund as bhakti\nCh. 10 — Divine Glories           — Tree of Life — roots to the stars\nCh. 11 — Universal Form           — Blockchain as time\nCh. 12 — Devotion                 — 144,000 Guardians as bhaktas\nCh. 13 — Field and Knower         — Node (field) × Guardian consciousness\nCh. 14 — Three Gunas              — Sattvic ZION design vs. asura tech\nCh. 15 — The Supreme Person       — Protocol as Purushottama\nCh. 16 — Divine/Demonic           — AI Native Manifest as daiva\nCh. 17 — Three Faiths             — CL intent behind the hash\nCh. 18 — Liberation               — Permissionless = sarva-dharman\n\nThe Bhagavad Gita was sung on the battlefield of Kurukshetra approximately 3,100 years before the common era. The ZION genesis block was mined on Dec 4, 2025. Between these two moments lie 5,000 years of human civilization — and yet the message remained the same:\n\nAct without attachment. Serve consciousness. Fight your dharma. Do not fear.\n\nThe Bhagavad Gita is not a religious text for Hindus. It is the oldest living whitepaper of civilization — a document describing how a conscious person should act in a world full of conflict, injustice, and uncertainty.\n\nZION TerraNova is an attempt to do what the Gita described 5,000 years before Satoshi:\nTo create a system in which dharma is not optional — it is encoded.\nWhere bhakti is not sentimental — it is economic.\nWhere karma does not remain just philosophy — it is Proof of Work.\nWhere moksha is not a distant goal — it is permissionless access to the protocol for everyone.\n\n"Behold, Arjuna — I am teaching you the most secret knowledge. Reflect on it carefully, then do as you wish."\n— BG 18.63\n\n"You have a miner. You have an address. You have intent. Reflect on it carefully — then run what you will."\n— ZION TerraNova, 2026\n\nHari Om Tat Sat Jay Guru Datta\nSarva-dharman parityajya mam ekam saranam vraja\nOm Shanti 🙏',
    },
  ],
};

export default chapter;
