import {
  Aperture,
  Armchair,
  ArrowLeft,
  ArrowRight,
  Atom,
  Bed,
  Bike,
  Book,
  BookOpen,
  Boxes,
  Brain,
  Calendar,
  CalendarDays,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  Compass,
  Cpu,
  Download,
  Droplet,
  Eye,
  ExternalLink,
  Facebook,
  Feather,
  FileArchive,
  FileText,
  Flag,
  FlaskConical,
  Flower2,
  Globe,
  Github,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  Headphones,
  Images,
  Infinity,
  Instagram,
  Landmark,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link as LinkIcon,
  List,
  LogIn,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Moon,
  Mountain,
  Paintbrush,
  Palette,
  PenTool,
  Pill,
  PlusCircle,
  Route,
  Rocket,
  Ruler,
  Scale,
  Search,
  Server,
  Shield,
  Shirt,
  ShoppingCart,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Tent,
  Thermometer,
  TreeDeciduous,
  TreePine,
  Twitter,
  Users,
  UtensilsCrossed,
  Wand2,
  Waves,
  Weight,
  Zap,
} from "lucide-react";

export const ICONS: Record<string, React.ComponentType<any>> = {
  // Actions / UI
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right-from-square": ExternalLink,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  download: Download,
  list: List,
  search: Search,
  link: LinkIcon,
  "external-link": ExternalLink,

  // Brand
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  "x-twitter": Twitter,
  github: Github,
  discord: MessageCircle,

  // Common
  atom: Atom,
  balance: Scale,
  "balance-scale": Scale,
  bed: Bed,
  bicycle: Bike,
  bike: Bike,
  bolt: Zap,
  book: Book,
  "book-bible": BookOpen,
  "book-open": BookOpen,
  "border-all": LayoutGrid,
  boxes: Boxes,
  brain: Brain,
  "building-columns": Landmark,
  bullhorn: Megaphone,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  campground: Tent,
  "cart-plus": PlusCircle,
  "cart-shopping": ShoppingCart,
  clock: Clock,
  comments: MessagesSquare,
  compass: Compass,
  couch: Armchair,
  cubes: Boxes,
  disc: Circle,
  door: LogIn,
  "door-open": LogIn,
  droplet: Droplet,
  eye: Eye,
  "face-grin-stars": Smile,
  "face-smile": Smile,
  feather: Feather,
  "file-archive": FileArchive,
  "file-lines": FileText,
  "file-zipper": FileArchive,
  flag: Flag,
  flask: FlaskConical,
  globe: Globe,
  "hand-holding-heart": HeartHandshake,
  handheart: HandHeart,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  "hat-wizard": Wand2,
  images: Images,
  infinity: Infinity,
  "leaf": Leaf,
  "leafy-green": Leaf,
  lightbulb: Lightbulb,
  "magic-sparkles": Wand2,
  megaphone: Megaphone,
  microchip: Cpu,
  moon: Moon,
  mountain: Mountain,
  "mountain-sun": Mountain,
  om: Infinity,
  paintbrush: Paintbrush,
  palette: Palette,
  "pen-nib": PenTool,
  pills: Pill,
  rocket: Rocket,
  "route": Route,
  "ruler-vertical": Ruler,
  scale: Scale,
  "scale-balanced": Scale,
  scroll: FileText,
  "scroll-text": FileText,
  seedling: Sprout,
  server: Server,
  shirt: Shirt,
  shield: Shield,
  "shield-halved": Shield,
  "shield-heart": Heart,
  smile: Smile,
  "solar-panel": Sun,
  spa: Flower2,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  "temperature-half": Thermometer,
  tent: Tent,
  tree: TreePine,
  users: Users,
  utensils: UtensilsCrossed,
  water: Waves,
  "wand-magic-sparkles": Wand2,
  waves: Waves,
  "weight-hanging": Weight,
  zap: Zap,
};
