[package]
name = "zion-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "node"
path = "src/bin/node.rs"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
ed25519-dalek.workspace = true
heed.workspace = true
rand.workspace = true
ripemd.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
zeroize.workspace = true
zion-cosmic-harmony = { path = "../cosmic-harmony" }

[dev-dependencies]
tempfile.workspace = true

[features]
default = []
testnet = []
